import JSZip from 'jszip';
import type { ProjectConfig } from '@stack-init/schema';
import { slugify, generatePrismaSchema, toTs } from './common';

export async function generateNestProject(zip: JSZip, config: ProjectConfig) {
  const { models, name: projectName } = config;
  const nestCfg = config.nest;
  const orm         = nestCfg?.orm || nestCfg?.database || 'prisma';
  const architecture = nestCfg?.architecture || 'modular';
  const isPrisma    = orm === 'prisma';
  const isTypeORM   = orm === 'typeorm';
  const isMongoose  = orm === 'mongoose';
  const isDrizzle   = orm === 'drizzle';
  const useSwagger  = nestCfg?.swagger ?? true;
  const useValidation = nestCfg?.validation ?? true;
  const useSerialization = nestCfg?.serialization ?? true;
  const useThrottling  = nestCfg?.throttling ?? false;
  const useAuth     = nestCfg?.auth === 'jwt';
  const isCqrs      = architecture === 'cqrs';
  const dbEngine    = nestCfg?.db_engine || 'postgresql';

  const dbUrl = dbEngine === 'mysql'
    ? `mysql://user:password@localhost:3306/${projectName}`
    : dbEngine === 'sqlite'
    ? `file:./dev.db`
    : `postgresql://user:password@localhost:5432/${projectName}?schema=public`;

  // ── package.json ─────────────────────────────────────────────────────────────

  const typeormDriver = dbEngine === 'mysql' ? 'mysql2' : dbEngine === 'sqlite' ? 'better-sqlite3' : 'pg';

  zip.file('package.json', JSON.stringify({
    name: projectName,
    version: '0.0.1',
    scripts: {
      start: 'nest start',
      'start:dev': 'nest start --watch',
      build: 'nest build',
      ...(isPrisma  && { 'prisma:generate': 'prisma generate', 'prisma:push': 'prisma db push' }),
      ...(isDrizzle && { 'db:generate': 'drizzle-kit generate', 'db:migrate': 'drizzle-kit migrate' }),
    },
    dependencies: {
      '@nestjs/common': '^11.0.0',
      '@nestjs/core': '^11.0.0',
      '@nestjs/config': '^4.0.0',
      '@nestjs/platform-express': '^11.0.0',
      'reflect-metadata': '^0.2.2',
      rxjs: '^7.8.1',
      ...(isPrisma   && { '@prisma/client': '^6.8.0' }),
      ...(isTypeORM  && { '@nestjs/typeorm': '^11.0.0', typeorm: '^0.3.21', [typeormDriver]: 'latest' }),
      ...(isMongoose && { '@nestjs/mongoose': '^11.0.0', mongoose: '^8.14.0' }),
      ...(isDrizzle  && { 'drizzle-orm': '^0.41.0', [typeormDriver]: 'latest' }),
      ...(useSwagger    && { '@nestjs/swagger': '^11.0.0' }),
      ...(useValidation && { 'class-validator': '^0.14.0', 'class-transformer': '^0.5.0' }),
      ...(useAuth       && { '@nestjs/jwt': '^11.0.0', '@nestjs/passport': '^11.0.0', passport: '^0.7.0', 'passport-jwt': '^4.0.0' }),
      ...(useThrottling && { '@nestjs/throttler': '^6.0.0' }),
      ...(isCqrs        && { '@nestjs/cqrs': '^11.0.0' }),
    },
    devDependencies: {
      '@nestjs/cli': '^11.0.0',
      '@nestjs/testing': '^11.0.0',
      typescript: '^5.8.3',
      ...(isPrisma   && { prisma: '^6.8.0' }),
      ...(isDrizzle  && { 'drizzle-kit': '^0.30.0' }),
      ...(useAuth    && { '@types/passport-jwt': '^3.0.0' }),
      ...(dbEngine === 'sqlite' && (isTypeORM || isDrizzle) && { '@types/better-sqlite3': '^7.6.11' }),
    },
  }, null, 2));

  zip.file('.env', `DATABASE_URL="${dbUrl}"\n${useAuth ? 'JWT_SECRET="stack-init-secret-change-me"\nJWT_EXPIRES_IN="7d"\n' : ''}`);

  const envExLines = [
    `NODE_ENV=development`,
    `PORT=3000`,
    isMongoose ? `MONGODB_URI="mongodb://localhost:27017/${projectName}"` : `DATABASE_URL="${dbUrl}"`,
    ...(useAuth ? [`JWT_SECRET="change-me-in-production"`, `JWT_EXPIRES_IN="7d"`] : []),
  ];
  zip.file('.env.example', envExLines.join('\n') + '\n');

  // ── main.ts ──────────────────────────────────────────────────────────────────

  const swaggerSetup = useSwagger ? `
  const swaggerConfig = new DocumentBuilder()
    .setTitle('${projectName} API')
    .setDescription('Generated by Stack-Init')
    .setVersion('1.0')
    .addBearerAuth()
    .build();
  SwaggerModule.setup('api/docs', app, SwaggerModule.createDocument(app, swaggerConfig));` : '';

  zip.file('src/main.ts', `import { NestFactory, Reflector } from '@nestjs/core';
import { ValidationPipe, ClassSerializerInterceptor } from '@nestjs/common';
import { AppModule } from './app.module';
${useSwagger ? "import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';" : ''}

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.enableCors();
${useValidation    ? "  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }));" : ''}
${useSerialization ? "  app.useGlobalInterceptors(new ClassSerializerInterceptor(app.get(Reflector)));" : ''}
${swaggerSetup}
  await app.listen(3000);
  console.log('🚀 Server running on http://localhost:3000');
}
bootstrap();
`);

  // ── ORM setup files ──────────────────────────────────────────────────────────

  if (isPrisma) {
    zip.file('prisma/schema.prisma', generatePrismaSchema(config));
    zip.file('src/prisma.service.ts', `import { Injectable, OnModuleInit } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
  async onModuleInit() { await this.$connect(); }
}
`);
  }

  if (isDrizzle) {
    const drizzleTable = dbEngine === 'mysql' ? 'mysqlTable' : dbEngine === 'sqlite' ? 'sqliteTable' : 'pgTable';
    const drizzleImport = dbEngine === 'mysql' ? `import { mysqlTable, serial, varchar } from 'drizzle-orm/mysql-core';`
      : dbEngine === 'sqlite' ? `import { sqliteTable, integer, text } from 'drizzle-orm/sqlite-core';`
      : `import { pgTable, serial, varchar } from 'drizzle-orm/pg-core';`;

    zip.file('src/db/schema.ts', `${drizzleImport}
// Define your tables here
// Example:
// export const users = ${drizzleTable}('users', { id: serial('id').primaryKey(), name: varchar('name', { length: 256 }) });
`);
    zip.file('src/db/index.ts', `import { drizzle } from 'drizzle-orm/${dbEngine === 'postgresql' ? 'node-postgres' : dbEngine === 'mysql' ? 'mysql2' : 'better-sqlite3'}';
import * as schema from './schema';

export const db = drizzle(process.env.DATABASE_URL as string, { schema });
`);
    zip.file('drizzle.config.ts', `import type { Config } from 'drizzle-kit';

export default {
  schema: './src/db/schema.ts',
  out: './drizzle',
  dialect: '${dbEngine === 'mysql' ? 'mysql' : dbEngine === 'sqlite' ? 'sqlite' : 'postgresql'}',
  dbCredentials: { url: process.env.DATABASE_URL! },
} satisfies Config;
`);
  }

  // ── Auth module ───────────────────────────────────────────────────────────────

  if (useAuth) {
    zip.file('src/auth/auth.module.ts', `import { Module } from '@nestjs/common';
import { JwtModule } from '@nestjs/jwt';
import { PassportModule } from '@nestjs/passport';
import { AuthService } from './auth.service';
import { JwtStrategy } from './jwt.strategy';

@Module({
  imports: [
    PassportModule,
    JwtModule.register({ secret: process.env.JWT_SECRET || 'secret', signOptions: { expiresIn: '1h' } }),
  ],
  providers: [AuthService, JwtStrategy],
  exports: [AuthService],
})
export class AuthModule {}
`);
    zip.file('src/auth/auth.service.ts', `import { Injectable } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';

@Injectable()
export class AuthService {
  constructor(private jwtService: JwtService) {}
  async generateToken(user: any) {
    return { access_token: this.jwtService.sign({ sub: user.id, email: user.email }) };
  }
}
`);
    zip.file('src/auth/jwt.strategy.ts', `import { Injectable } from '@nestjs/common';
import { PassportStrategy } from '@nestjs/passport';
import { ExtractJwt, Strategy } from 'passport-jwt';

@Injectable()
export class JwtStrategy extends PassportStrategy(Strategy) {
  constructor() {
    super({ jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(), ignoreExpiration: false, secretOrKey: process.env.JWT_SECRET || 'secret' });
  }
  async validate(payload: any) { return { userId: payload.sub, email: payload.email }; }
}
`);
    zip.file('src/auth/jwt-auth.guard.ts', `import { Injectable } from '@nestjs/common';
import { AuthGuard } from '@nestjs/passport';

@Injectable()
export class JwtAuthGuard extends AuthGuard('jwt') {}
`);
  }

  // ── app.module.ts ─────────────────────────────────────────────────────────────

  const typeormEntities = isTypeORM
    ? `TypeOrmModule.forRootAsync({ useFactory: () => ({ type: '${dbEngine === 'mysql' ? 'mysql' : dbEngine === 'sqlite' ? 'better-sqlite3' : 'postgres'}', url: process.env.DATABASE_URL, entities: [__dirname + '/**/*.entity{.ts,.js}'], synchronize: process.env.NODE_ENV !== 'production', }) }),`
    : '';
  const mongooseRoot = isMongoose
    ? `MongooseModule.forRoot(process.env.DATABASE_URL!),`
    : '';
  const throttlerModule = useThrottling
    ? `ThrottlerModule.forRoot([{ ttl: 60000, limit: 10 }]),`
    : '';

  zip.file('src/app.module.ts', `import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
${isTypeORM   ? "import { TypeOrmModule } from '@nestjs/typeorm';" : ''}
${isMongoose  ? "import { MongooseModule } from '@nestjs/mongoose';" : ''}
${useThrottling ? "import { ThrottlerModule, ThrottlerGuard } from '@nestjs/throttler';\nimport { APP_GUARD } from '@nestjs/core';" : ''}
${useAuth ? "import { AuthModule } from './auth/auth.module';" : ''}
${models.map(m => `import { ${m.name}Module } from './${slugify(m.name)}/${slugify(m.name)}.module';`).join('\n')}

@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    ${typeormEntities}
    ${mongooseRoot}
    ${throttlerModule}
    ${useAuth ? 'AuthModule,' : ''}
    ${models.map(m => `${m.name}Module`).join(', ')}
  ],
  ${useThrottling ? "providers: [{ provide: APP_GUARD, useClass: ThrottlerGuard }]," : ''}
})
export class AppModule {}
`);

  // ── Per-model files ───────────────────────────────────────────────────────────

  for (const model of models) {
    const slug = slugify(model.name);
    const mLow = model.name.toLowerCase();

    // DTOs with validation decorators
    const dtoFields = model.fields.map(f => {
      const decorators: string[] = [];
      if (useSwagger)    decorators.push(`  @ApiProperty({ required: ${!f.nullable} })`);
      if (useValidation) {
        if (f.nullable) decorators.push('  @IsOptional()');
        switch (f.type) {
          case 'string': case 'text': case 'char': case 'uuid': case 'ulid': decorators.push('  @IsString()'); break;
          case 'integer': case 'smallInteger': case 'tinyInteger': case 'mediumInteger': case 'bigInteger': decorators.push('  @IsInt()'); break;
          case 'float': case 'double': case 'decimal': decorators.push('  @IsNumber()'); break;
          case 'boolean': decorators.push('  @IsBoolean()'); break;
          case 'date': case 'dateTime': case 'timestamp': decorators.push('  @IsDateString()'); break;
          case 'email': decorators.push('  @IsEmail()'); break;
          case 'enum': if (f.values?.length) decorators.push(`  @IsIn([${f.values.map(v => `'${v}'`).join(', ')}])`); break;
        }
      }
      return `${decorators.join('\n')}\n  ${f.name}${f.nullable ? '?' : ''}: ${toTs(f.type)};`;
    }).join('\n\n');

    const validatorImports = useValidation
      ? 'IsString, IsNumber, IsBoolean, IsOptional, IsInt, IsUUID, IsDateString, IsIn, IsEmail'
      : '';

    zip.file(`src/${slug}/dto/create-${slug}.dto.ts`, `${useSwagger ? "import { ApiProperty } from '@nestjs/swagger';" : ''}
${useValidation ? `import { ${validatorImports} } from 'class-validator';` : ''}

export class Create${model.name}Dto {
${dtoFields}
}
`);

    zip.file(`src/${slug}/dto/update-${slug}.dto.ts`, `import { PartialType } from '${useSwagger ? '@nestjs/swagger' : '@nestjs/mapped-types'}';
import { Create${model.name}Dto } from './create-${slug}.dto';

export class Update${model.name}Dto extends PartialType(Create${model.name}Dto) {}
`);

    // TypeORM entity
    if (isTypeORM) {
      const typeormFields = model.fields.map(f => {
        let colType = 'varchar';
        switch (f.type) {
          case 'integer': case 'tinyInteger': case 'smallInteger': colType = 'int'; break;
          case 'bigInteger': colType = 'bigint'; break;
          case 'float': case 'double': colType = 'float'; break;
          case 'decimal': colType = 'decimal'; break;
          case 'boolean': colType = 'boolean'; break;
          case 'date': colType = 'date'; break;
          case 'dateTime': case 'timestamp': colType = 'timestamp'; break;
          case 'text': case 'longText': colType = 'text'; break;
          case 'json': case 'jsonb': colType = 'json'; break;
          case 'uuid': colType = 'uuid'; break;
        }
        const colOpts = [`type: '${colType}'`, f.nullable ? 'nullable: true' : 'nullable: false'].join(', ');
        return `  @Column({ ${colOpts} })\n  ${f.name}${f.nullable ? '?' : '!'}: ${toTs(f.type)};`;
      }).join('\n\n');

      zip.file(`src/${slug}/entities/${slug}.entity.ts`, `import { Entity, PrimaryGeneratedColumn, Column${model.migration?.timestamps ? ', CreateDateColumn, UpdateDateColumn' : ''} } from 'typeorm';

@Entity('${model.table || mLow}s')
export class ${model.name} {
  @PrimaryGeneratedColumn()
  id!: number;

${typeormFields}
${model.migration?.timestamps ? `
  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;` : ''}
}
`);
    }

    // Mongoose schema
    if (isMongoose) {
      const schemaProps = model.fields.map(f => {
        let propType = 'String';
        switch (f.type) {
          case 'integer': case 'float': case 'double': case 'decimal': case 'bigInteger': propType = 'Number'; break;
          case 'boolean': propType = 'Boolean'; break;
          case 'date': case 'dateTime': case 'timestamp': propType = 'Date'; break;
          case 'json': case 'jsonb': propType = 'Object'; break;
        }
        return `  @Prop({ required: ${!f.nullable}${f.unique ? ', unique: true' : ''} })\n  ${f.name}!: ${toTs(f.type)};`;
      }).join('\n\n');

      zip.file(`src/${slug}/${slug}.schema.ts`, `import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';

export type ${model.name}Document = HydratedDocument<${model.name}>;

@Schema({ timestamps: ${!!model.migration?.timestamps} })
export class ${model.name} {
${schemaProps}
}

export const ${model.name}Schema = SchemaFactory.createForClass(${model.name});
`);
    }

    // Entity for serialization (Prisma / none)
    if (isPrisma || orm === 'none') {
      const entityFields = model.fields.map(f => {
        const dec = f.name === 'password' && useSerialization ? '  @Exclude()\n' : '';
        return `${dec}  ${f.name}: ${toTs(f.type)};`;
      }).join('\n');

      zip.file(`src/${slug}/entities/${slug}.entity.ts`, `${useSerialization ? "import { Exclude } from 'class-transformer';" : ''}

export class ${model.name}Entity {
  id: number;
${entityFields}
  constructor(partial: Partial<${model.name}Entity>) { Object.assign(this, partial); }
}
`);
    }

    // Module
    const moduleTypeOrmImport   = isTypeORM  ? `\nimport { TypeOrmModule } from '@nestjs/typeorm';\nimport { ${model.name} } from './entities/${slug}.entity';` : '';
    const moduleMongooseImport  = isMongoose ? `\nimport { MongooseModule } from '@nestjs/mongoose';\nimport { ${model.name}, ${model.name}Schema } from './${slug}.schema';` : '';
    const moduleImportsArr      = [
      isPrisma   ? 'PrismaService'                : '',
      isTypeORM  ? `TypeOrmModule.forFeature([${model.name}])` : '',
      isMongoose ? `MongooseModule.forFeature([{ name: ${model.name}.name, schema: ${model.name}Schema }])` : '',
    ].filter(Boolean).join(', ');

    zip.file(`src/${slug}/${slug}.module.ts`, `import { Module } from '@nestjs/common';
import { ${model.name}Controller } from './${slug}.controller';
import { ${model.name}Service } from './${slug}.service';
${isPrisma  ? "import { PrismaService } from '../prisma.service';" : ''}${moduleTypeOrmImport}${moduleMongooseImport}
${isCqrs ? `import { CqrsModule } from '@nestjs/cqrs';\nimport { Create${model.name}Handler } from './commands/handlers/create-${slug}.handler';\nimport { GetAll${model.name}Handler } from './queries/handlers/get-all-${slug}.handler';` : ''}

@Module({
  imports: [${isCqrs ? `CqrsModule, ` : ''}${isTypeORM ? `TypeOrmModule.forFeature([${model.name}])` : ''}${isMongoose ? `MongooseModule.forFeature([{ name: ${model.name}.name, schema: ${model.name}Schema }])` : ''}],
  controllers: [${model.name}Controller],
  providers: [${model.name}Service${isPrisma ? ', PrismaService' : ''}${isCqrs ? `, Create${model.name}Handler, GetAll${model.name}Handler` : ''}],
})
export class ${model.name}Module {}
`);

    // Controller
    zip.file(`src/${slug}/${slug}.controller.ts`, `import { Controller, Get, Post, Body, Patch, Param, Delete${useAuth ? ', UseGuards' : ''} } from '@nestjs/common';
${useSwagger ? `import { ApiTags, ApiOperation${useAuth ? ', ApiBearerAuth' : ''} } from '@nestjs/swagger';` : ''}
import { ${model.name}Service } from './${slug}.service';
import { Create${model.name}Dto } from './dto/create-${slug}.dto';
import { Update${model.name}Dto } from './dto/update-${slug}.dto';
${useAuth ? "import { JwtAuthGuard } from '../auth/jwt-auth.guard';" : ''}

${useSwagger ? `@ApiTags('${model.name}')` : ''}
@Controller('${slug}')
export class ${model.name}Controller {
  constructor(private readonly service: ${model.name}Service) {}

  @Post()
  ${useSwagger ? `@ApiOperation({ summary: 'Create ${mLow}' })` : ''}
  ${useAuth ? `@UseGuards(JwtAuthGuard)\n  @ApiBearerAuth()` : ''}
  create(@Body() dto: Create${model.name}Dto) { return this.service.create(dto); }

  @Get()
  ${useSwagger ? `@ApiOperation({ summary: 'Get all ${mLow}s' })` : ''}
  findAll() { return this.service.findAll(); }

  @Get(':id')
  ${useSwagger ? `@ApiOperation({ summary: 'Get one ${mLow}' })` : ''}
  findOne(@Param('id') id: string) { return this.service.findOne(+id); }

  @Patch(':id')
  ${useSwagger ? `@ApiOperation({ summary: 'Update ${mLow}' })` : ''}
  ${useAuth ? `@UseGuards(JwtAuthGuard)\n  @ApiBearerAuth()` : ''}
  update(@Param('id') id: string, @Body() dto: Update${model.name}Dto) { return this.service.update(+id, dto); }

  @Delete(':id')
  ${useSwagger ? `@ApiOperation({ summary: 'Delete ${mLow}' })` : ''}
  ${useAuth ? `@UseGuards(JwtAuthGuard)\n  @ApiBearerAuth()` : ''}
  remove(@Param('id') id: string) { return this.service.remove(+id); }
}
`);

    // Service
    const svcInject = isPrisma
      ? `constructor(private prisma: PrismaService) {}`
      : isTypeORM
      ? `constructor(@InjectRepository(${model.name}) private repo: Repository<${model.name}>) {}`
      : isMongoose
      ? `constructor(@InjectModel(${model.name}.name) private model: Model<${model.name}Document>) {}`
      : '';

    const svcCreate = isPrisma ? `this.prisma.${mLow}.create({ data: dto })`
      : isTypeORM  ? `this.repo.save(this.repo.create(dto))`
      : isMongoose ? `this.model.create(dto)`
      : `{ id: Date.now(), ...dto }`;
    const svcFindAll = isPrisma ? `this.prisma.${mLow}.findMany()`
      : isTypeORM  ? `this.repo.find()`
      : isMongoose ? `this.model.find().exec()`
      : `[]`;
    const svcFindOne = isPrisma ? `this.prisma.${mLow}.findUnique({ where: { id } })`
      : isTypeORM  ? `this.repo.findOne({ where: { id } })`
      : isMongoose ? `this.model.findById(id).exec()`
      : `null`;
    const svcUpdate = isPrisma ? `this.prisma.${mLow}.update({ where: { id }, data: dto })`
      : isTypeORM  ? `(async () => { await this.repo.update(id, dto); return this.repo.findOne({ where: { id } }); })()`
      : isMongoose ? `this.model.findByIdAndUpdate(id, dto, { new: true }).exec()`
      : `{ id, ...dto }`;
    const svcRemove = isPrisma ? `this.prisma.${mLow}.delete({ where: { id } })`
      : isTypeORM  ? `this.repo.delete(id)`
      : isMongoose ? `this.model.findByIdAndDelete(id).exec()`
      : `{ id }`;

    const svcImports = [
      isPrisma   ? "import { PrismaService } from '../prisma.service';" : '',
      isTypeORM  ? `import { InjectRepository } from '@nestjs/typeorm';\nimport { Repository } from 'typeorm';\nimport { ${model.name} } from './entities/${slug}.entity';` : '',
      isMongoose ? `import { InjectModel } from '@nestjs/mongoose';\nimport { Model } from 'mongoose';\nimport { ${model.name}, ${model.name}Document } from './${slug}.schema';` : '',
    ].filter(Boolean).join('\n');

    zip.file(`src/${slug}/${slug}.service.ts`, `import { Injectable } from '@nestjs/common';
${svcImports}
import { Create${model.name}Dto } from './dto/create-${slug}.dto';
import { Update${model.name}Dto } from './dto/update-${slug}.dto';

@Injectable()
export class ${model.name}Service {
  ${svcInject}

  async create(dto: Create${model.name}Dto) { return ${svcCreate}; }
  async findAll() { return ${svcFindAll}; }
  async findOne(id: number) { return ${svcFindOne}; }
  async update(id: number, dto: Update${model.name}Dto) { return ${svcUpdate}; }
  async remove(id: number) { return ${svcRemove}; }
}
`);

    // CQRS handlers
    if (isCqrs) {
      zip.file(`src/${slug}/commands/create-${slug}.command.ts`, `import { ICommand } from '@nestjs/cqrs';
import { Create${model.name}Dto } from '../dto/create-${slug}.dto';

export class Create${model.name}Command implements ICommand {
  constructor(public readonly dto: Create${model.name}Dto) {}
}
`);
      zip.file(`src/${slug}/commands/handlers/create-${slug}.handler.ts`, `import { CommandHandler, ICommandHandler } from '@nestjs/cqrs';
import { Create${model.name}Command } from '../create-${slug}.command';
import { ${model.name}Service } from '../../${slug}.service';

@CommandHandler(Create${model.name}Command)
export class Create${model.name}Handler implements ICommandHandler<Create${model.name}Command> {
  constructor(private readonly service: ${model.name}Service) {}
  async execute(command: Create${model.name}Command) {
    return this.service.create(command.dto);
  }
}
`);
      zip.file(`src/${slug}/queries/get-all-${slug}.query.ts`, `import { IQuery } from '@nestjs/cqrs';

export class GetAll${model.name}Query implements IQuery {}
`);
      zip.file(`src/${slug}/queries/handlers/get-all-${slug}.handler.ts`, `import { QueryHandler, IQueryHandler } from '@nestjs/cqrs';
import { GetAll${model.name}Query } from '../get-all-${slug}.query';
import { ${model.name}Service } from '../../${slug}.service';

@QueryHandler(GetAll${model.name}Query)
export class GetAll${model.name}Handler implements IQueryHandler<GetAll${model.name}Query> {
  constructor(private readonly service: ${model.name}Service) {}
  async execute() { return this.service.findAll(); }
}
`);
    }
  }
}
