import JSZip from 'jszip';
import type { ProjectConfig, Model, ModelPages, ReactOptions } from '@stack-init/schema';
import { slugify, generatePrismaSchema, buildDeps, toTs } from './common';

const DEFAULT_PAGES: ModelPages = { list: true, detail: true, create: true, edit: false };

export async function generateNextjsProject(zip: JSZip, config: ProjectConfig) {
  const { react: reactOpts, models, name: projectName, stack } = config;
  const opts: ReactOptions = reactOpts ?? {} as ReactOptions;
  const isFullStack = stack === 'nextjs' && config.nextjsUsage === 'full-stack';

  // package.json
  const dependencies = buildDeps(opts);
  if (isFullStack) {
    dependencies['@prisma/client'] = '^6.8.0';
  }

  zip.file('package.json', JSON.stringify({
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      ...(isFullStack && {
        "prisma:generate": "prisma generate",
        "prisma:studio": "prisma studio",
        "db:seed": "tsx prisma/seed.ts",
      })
    },
    dependencies,
    devDependencies: {
      typescript: '^5.8.3',
      '@types/node': '^22.15.3',
      '@types/react': '^19.1.0',
      '@types/react-dom': '^19.1.0',
      ...(isFullStack && { prisma: '^6.8.0', tsx: '^4.19.2' })
    },
  }, null, 2));

  // Prisma Schema (if fullstack)
  if (isFullStack) {
    zip.file('prisma/schema.prisma', generatePrismaSchema(config));
    zip.file('prisma/seed.ts', generatePrismaSeed(models));
    zip.file('src/lib/prisma.ts', `import { PrismaClient } from '@prisma/client';

const globalForPrisma = global as unknown as { prisma: PrismaClient };

export const prisma = globalForPrisma.prisma || new PrismaClient();

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;
`);
  }

  // tsconfig.json
  zip.file('tsconfig.json', JSON.stringify({
    compilerOptions: {
      target: 'ES2017',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'react-jsx',
      incremental: true,
      paths: { '@/*': ['./src/*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
    exclude: ['node_modules'],
  }, null, 2));

  // next.config.ts
  zip.file('next.config.ts', `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {};

export default nextConfig;
`);

  // tailwind
  if (opts.css === 'tailwind') {
    zip.file('tailwind.config.ts', `import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
};

export default config;
`);
    zip.file('postcss.config.mjs', `const config = {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};

export default config;
`);
    zip.file('src/app/globals.css', `@import "tailwindcss";
`);
  } else {
    zip.file('src/app/globals.css', `* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: system-ui, sans-serif; }
`);
  }

  // src/app/layout.tsx
  const muiLayout   = opts.ui_lib === 'mui';
  const antdLayout  = opts.ui_lib === 'antd';

  const layoutImports = [
    opts.css === 'tailwind' ? "import './globals.css';" : '',
    muiLayout  ? "import { ThemeProvider, createTheme } from '@mui/material/styles';\nimport CssBaseline from '@mui/material/CssBaseline';" : '',
    antdLayout ? "import { ConfigProvider } from 'antd';" : '',
  ].filter(Boolean).join('\n');

  const layoutInner = muiLayout
    ? `      <ThemeProvider theme={createTheme()}><CssBaseline />{children}</ThemeProvider>`
    : antdLayout
    ? `      <ConfigProvider>{children}</ConfigProvider>`
    : `      {children}`;

  zip.file('src/app/layout.tsx', `import type { Metadata } from 'next';
${layoutImports}

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by Stack-Init',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
${layoutInner}
      </body>
    </html>
  );
}
`);

  // src/app/page.tsx
  zip.file('src/app/page.tsx', generateHomePage(models, projectName, opts));

  // State management
  if (opts.state_lib === 'zustand') {
    zip.file('src/stores/useAppStore.ts', `import { create } from 'zustand';

interface AppState {
  counter: number;
  increment: () => void;
  decrement: () => void;
}

export const useAppStore = create<AppState>((set) => ({
  counter: 0,
  increment: () => set((state) => ({ counter: state.counter + 1 })),
  decrement: () => set((state) => ({ counter: state.counter - 1 })),
}));
`);
  }

  if (opts.state_lib === 'redux-toolkit') {
    zip.file('src/store/index.ts', `import { configureStore } from '@reduxjs/toolkit';
import counterReducer from './slices/counterSlice';

export const store = configureStore({
  reducer: {
    counter: counterReducer,
  },
});

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
`);
    zip.file('src/store/hooks.ts', `import { TypedUseSelectorHook, useDispatch, useSelector } from 'react-redux';
import type { RootState, AppDispatch } from '.';

export const useAppDispatch = () => useDispatch<AppDispatch>();
export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector;
`);
    zip.file('src/store/slices/counterSlice.ts', `import { createSlice } from '@reduxjs/toolkit';

interface CounterState { value: number; }
const initialState: CounterState = { value: 0 };

export const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
    increment: (state) => { state.value += 1; },
    decrement: (state) => { state.value -= 1; },
  },
});

export const { increment, decrement } = counterSlice.actions;
export default counterSlice.reducer;
`);
  }

  if (opts.state_lib === 'jotai') {
    zip.file('src/atoms/index.ts', `import { atom } from 'jotai';

export const counterAtom = atom(0);
export const loadingAtom = atom(false);
`);
  }

  // Per-model TypeScript interfaces + pages
  for (const model of models) {
    const slug = slugify(model.name);
    const pages: ModelPages = { ...DEFAULT_PAGES, ...model.pages };

    // API Routes (if fullstack)
    if (isFullStack) {
      zip.file(`src/app/api/${slug}/route.ts`, generateApiRoute(model));
      zip.file(`src/app/api/${slug}/[id]/route.ts`, generateApiIdRoute(model));
    }

    // src/types/[ModelName].ts
    const fieldLines = model.fields
      .map((f) => `  ${f.name}${f.nullable ? '?' : ''}: ${f.values?.length ? f.values.map(v => `'${v}'`).join(' | ') : toTs(f.type)};`)
      .join('\n');
    zip.file(`src/types/${model.name}.ts`, `export interface ${model.name} {
  id: number;
${fieldLines}
  created_at: string;
  updated_at: string;
}
`);

    const apiBase = isFullStack ? `/api/${slug}` : `http://localhost:3000/api/${slug}`;

    if (pages.list) {
      zip.file(`src/app/${slug}/page.tsx`, generateListPage(model, apiBase, pages, opts));
    }
    if (pages.detail) {
      zip.file(`src/app/${slug}/[id]/page.tsx`, generateDetailPage(model, apiBase, pages, opts));
    }
    if (pages.create) {
      zip.file(`src/app/${slug}/new/page.tsx`, generateCreatePage(model, apiBase, slug, opts));
    }
    if (pages.edit) {
      zip.file(`src/app/${slug}/[id]/edit/page.tsx`, generateEditPage(model, apiBase, slug, opts));
    }
  }
}

function generateApiRoute(model: Model): string {
  return `import { prisma } from '@/lib/prisma';
import { NextResponse } from 'next/server';

export async function GET() {
  const items = await prisma.${model.name.toLowerCase()}.findMany();
  return NextResponse.json(items);
}

export async function POST(req: Request) {
  const data = await req.json();
  const item = await prisma.${model.name.toLowerCase()}.create({ data });
  return NextResponse.json(item);
}
`;
}

function generateApiIdRoute(model: Model): string {
  const mLow = model.name.toLowerCase();
  return `import { prisma } from '@/lib/prisma';
import { NextResponse } from 'next/server';

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const item = await prisma.${mLow}.findUnique({ where: { id: parseInt(id) } });
  return NextResponse.json(item);
}

export async function PATCH(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const data = await req.json();
  const item = await prisma.${mLow}.update({ where: { id: parseInt(id) }, data });
  return NextResponse.json(item);
}

export async function DELETE(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  await prisma.${mLow}.delete({ where: { id: parseInt(id) } });
  return new NextResponse(null, { status: 204 });
}
`;
}

function generateListPage(model: Model, apiBase: string, pages: ModelPages, opts?: ReactOptions | null): string {
  const slug = slugify(model.name);
  const firstField = model.fields[0]?.name ?? 'id';
  const uiLib = opts?.ui_lib ?? 'none';
  const useTailwind = opts?.css === 'tailwind' || uiLib === 'shadcn' || uiLib === 'tailwind';

  const fetchBlock = `async function getData() {
  const res = await fetch('${apiBase}', { cache: 'no-store' });
  if (!res.ok) throw new Error('Failed to fetch');
  return res.json();
}`;

  if (uiLib === 'mui') {
    return `import Link from 'next/link';
import { Container, Typography, Stack, Card, CardContent, CardActions, Button } from '@mui/material';

${fetchBlock}

export default async function ${model.name}ListPage() {
  const items = await getData();
  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Stack direction="row" justifyContent="space-between" alignItems="center" mb={3}>
        <Typography variant="h4">${model.name}s</Typography>
        ${pages.create ? `<Button component={Link} href="/${slug}/new" variant="contained">+ New</Button>` : ''}
      </Stack>
      <Stack spacing={2}>
        {items.map((item: any) => (
          <Card key={item.id} variant="outlined">
            <CardContent>
              <Typography>#{item.id} &ndash; {item.${firstField}}</Typography>
            </CardContent>
            ${pages.detail ? `<CardActions><Button component={Link} href={\`/${slug}/\${item.id}\`} size="small">View &rarr;</Button></CardActions>` : ''}
          </Card>
        ))}
      </Stack>
    </Container>
  );
}
`;
  }

  if (uiLib === 'antd') {
    return `'use client';
import Link from 'next/link';
import { Typography, List, Button, Space } from 'antd';
import { useEffect, useState } from 'react';

export default function ${model.name}ListPage() {
  const [items, setItems] = useState<any[]>([]);

  useEffect(() => {
    fetch('${apiBase}').then(r => r.json()).then(setItems);
  }, []);

  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: '2rem' }}>
      <Space style={{ width: '100%', justifyContent: 'space-between', marginBottom: 24 }}>
        <Typography.Title level={3} style={{ margin: 0 }}>${model.name}s</Typography.Title>
        ${pages.create ? `<Link href="/${slug}/new"><Button type="primary">+ New</Button></Link>` : ''}
      </Space>
      <List
        bordered
        dataSource={items}
        renderItem={(item: any) => (
          <List.Item
            actions={[${pages.detail ? `<Link key="view" href={\`/${slug}/\${item.id}\`}>View &rarr;</Link>` : ''}]}
          >
            #{item.id} &ndash; {item.${firstField}}
          </List.Item>
        )}
      />
    </div>
  );
}
`;
  }

  if (useTailwind) {
    const newLink = pages.create
      ? `<Link href="/${slug}/new" className="px-4 py-2 bg-black text-white rounded-md text-sm hover:bg-gray-800 no-underline">+ New</Link>`
      : '';
    const viewLink = pages.detail
      ? `<Link href={\`/${slug}/\${item.id}\`} className="text-sm text-indigo-500 hover:underline">View &rarr;</Link>`
      : '';
    return `import Link from 'next/link';

${fetchBlock}

export default async function ${model.name}ListPage() {
  const items = await getData();
  return (
    <main className="p-8 max-w-4xl mx-auto">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">${model.name}s</h1>
        ${newLink}
      </div>
      <ul className="flex flex-col gap-2 list-none p-0">
        {items.map((item: any) => (
          <li key={item.id} className="border rounded-lg px-4 py-3 flex justify-between items-center hover:bg-gray-50">
            <span className="text-sm">#{item.id} &ndash; {item.${firstField}}</span>
            ${viewLink}
          </li>
        ))}
      </ul>
    </main>
  );
}
`;
  }

  // Default: inline styles
  const newLink = pages.create
    ? `<Link href="/${slug}/new" style={{ padding: '8px 16px', background: '#000', color: '#fff', borderRadius: 6, textDecoration: 'none' }}>+ New</Link>`
    : '';
  const viewLink = pages.detail
    ? `<Link href={\`/${slug}/\${item.id}\`} style={{ fontSize: 14, color: '#6366f1' }}>View &rarr;</Link>`
    : '';
  return `import Link from 'next/link';

${fetchBlock}

export default async function ${model.name}ListPage() {
  const items = await getData();
  return (
    <main style={{ padding: '2rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
        <h1>${model.name}s</h1>
        ${newLink}
      </div>
      <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: 8 }}>
        {items.map((item: any) => (
          <li key={item.id} style={{ border: '1px solid #e5e7eb', borderRadius: 8, padding: '12px 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span>#{item.id} &ndash; {item.${firstField}}</span>
            ${viewLink}
          </li>
        ))}
      </ul>
    </main>
  );
}
`;
}

function generateDetailPage(model: Model, apiBase: string, pages: ModelPages, opts?: ReactOptions | null): string {
  const slug = slugify(model.name);
  const fields = model.fields.slice(0, 6);
  const uiLib = opts?.ui_lib ?? 'none';
  const useTailwind = opts?.css === 'tailwind' || uiLib === 'shadcn' || uiLib === 'tailwind';

  if (uiLib === 'mui') {
    const fieldRows = fields.map(f =>
      `            <Stack direction="row" justifyContent="space-between"><Typography fontWeight={600}>${f.name}</Typography><Typography>{String(item.${f.name} ?? '\u2014')}</Typography></Stack>`
    ).join('\n');
    const editAction = pages.edit
      ? `        <CardActions>\n          <Button component={Link} href={\`/${slug}/\${id}/edit\`} variant="outlined" size="small">Edit</Button>\n        </CardActions>`
      : '';
    return `import Link from 'next/link';
import { Container, Typography, Stack, Card, CardContent, CardActions, Button, Divider } from '@mui/material';

async function getData(id: string) {
  const res = await fetch(\`${apiBase}/\${id}\`, { cache: 'no-store' });
  if (!res.ok) throw new Error('Failed to fetch');
  return res.json();
}

export default async function ${model.name}DetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const item = await getData(id);
  return (
    <Container maxWidth="sm" sx={{ py: 4 }}>
      <Button component={Link} href="/${slug}" size="small" sx={{ mb: 2 }}>&larr; Back</Button>
      <Typography variant="h4" gutterBottom>${model.name} #{'{'}item.id{'}'}</Typography>
      <Card variant="outlined">
        <CardContent>
          <Stack spacing={1} divider={<Divider />}>
${fieldRows}
          </Stack>
        </CardContent>
${editAction}
      </Card>
    </Container>
  );
}
`;
  }

  if (uiLib === 'antd') {
    const descItems = fields.map(f =>
      `            <Descriptions.Item label="${f.name}">{String(item.${f.name} ?? '\u2014')}</Descriptions.Item>`
    ).join('\n');
    const editBtn = pages.edit ? `\n        <Link href={\`/${slug}/\${id}/edit\`}><Button>Edit</Button></Link>` : '';
    return `'use client';
import Link from 'next/link';
import { Typography, Card, Descriptions, Button, Space } from 'antd';
import { useEffect, useState } from 'react';

export default function ${model.name}DetailPage({ params }: { params: { id: string } }) {
  const { id } = params;
  const [item, setItem] = useState<any>(null);

  useEffect(() => {
    fetch(\`${apiBase}/\${id}\`).then(r => r.json()).then(setItem);
  }, [id]);

  if (!item) return <p>Loading...</p>;

  return (
    <div style={{ maxWidth: 600, margin: '0 auto', padding: '2rem' }}>
      <Space direction="vertical" style={{ width: '100%' }}>
        <Link href="/${slug}">&larr; Back</Link>
        <Typography.Title level={3}>${model.name} #{'{'}item.id{'}'}</Typography.Title>
        <Card>
          <Descriptions column={1} bordered>
${descItems}
          </Descriptions>
        </Card>${editBtn}
      </Space>
    </div>
  );
}
`;
  }

  if (useTailwind) {
    const fieldRows = fields.map(f =>
      `        <dt className="font-semibold text-sm">${f.name}</dt><dd className="text-sm">{String(item.${f.name} ?? '\u2014')}</dd>`
    ).join('\n');
    const editLink = pages.edit
      ? `\n        <Link href={\`/${slug}/\${id}/edit\`} className="px-4 py-2 border border-black rounded-md text-sm hover:bg-gray-50 no-underline">Edit</Link>`
      : '';
    return `import Link from 'next/link';

async function getData(id: string) {
  const res = await fetch(\`${apiBase}/\${id}\`, { cache: 'no-store' });
  if (!res.ok) throw new Error('Failed to fetch');
  return res.json();
}

export default async function ${model.name}DetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const item = await getData(id);
  return (
    <main className="p-8 max-w-2xl mx-auto">
      <Link href="/${slug}" className="text-sm text-indigo-500 hover:underline">&larr; Back</Link>
      <h1 className="text-2xl font-bold mt-4 mb-6">${model.name} #{'{'}item.id{'}'}</h1>
      <dl className="grid gap-x-4 gap-y-2" style={{ gridTemplateColumns: '140px 1fr' }}>
${fieldRows}
      </dl>${editLink ? `\n      <div className="mt-6 flex gap-3">${editLink}\n      </div>` : ''}
    </main>
  );
}
`;
  }

  // Default: inline styles
  const fieldRows = fields.map(f =>
    `        <dt style={{ fontWeight: 600 }}>${f.name}</dt><dd>{String(item.${f.name} ?? '\u2014')}</dd>`
  ).join('\n');
  const editLink = pages.edit
    ? `\n        <Link href={\`/${slug}/\${id}/edit\`} style={{ padding: '8px 16px', border: '1px solid #000', borderRadius: 6, textDecoration: 'none' }}>Edit</Link>`
    : '';
  return `import Link from 'next/link';

async function getData(id: string) {
  const res = await fetch(\`${apiBase}/\${id}\`, { cache: 'no-store' });
  if (!res.ok) throw new Error('Failed to fetch');
  return res.json();
}

export default async function ${model.name}DetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const item = await getData(id);
  return (
    <main style={{ padding: '2rem', maxWidth: 600 }}>
      <Link href="/${slug}" style={{ fontSize: 14, color: '#6366f1' }}>&larr; Back</Link>
      <h1 style={{ margin: '1rem 0' }}>${model.name} #{'{'}item.id{'}'}</h1>
      <dl style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: '8px 16px' }}>
${fieldRows}
      </dl>${editLink ? `\n      <div style={{ marginTop: '1.5rem', display: 'flex', gap: 12 }}>${editLink}\n      </div>` : ''}
    </main>
  );
}
`;
}


function generateCreatePage(model: Model, apiBase: string, slug: string, opts?: ReactOptions | null): string {
  const fields = model.fields.filter(f => f.type !== 'foreignId');
  const formLib = opts?.form_lib ?? 'none';
  const uiLib = opts?.ui_lib ?? 'none';

  if (formLib === 'react-hook-form') {
    return generateCreatePageRHF(model, apiBase, slug, uiLib, fields);
  }
  if (formLib === 'formik') {
    return generateCreatePageFormik(model, apiBase, slug, uiLib, fields);
  }
  return generateCreatePageVanilla(model, apiBase, slug, uiLib, fields);
}

function generateEditPage(model: Model, apiBase: string, slug: string, opts?: ReactOptions | null): string {
  const fields = model.fields.filter(f => f.type !== 'foreignId');
  const formLib = opts?.form_lib ?? 'none';
  const uiLib = opts?.ui_lib ?? 'none';

  if (formLib === 'react-hook-form') {
    return generateEditPageRHF(model, apiBase, slug, uiLib, fields);
  }
  if (formLib === 'formik') {
    return generateEditPageFormik(model, apiBase, slug, uiLib, fields);
  }
  return generateEditPageVanilla(model, apiBase, slug, uiLib, fields);
}

function uiInput(uiLib: string, field: { name: string }, valueExpr: string, onChangeExpr: string): string {
  if (uiLib === 'mui') {
    return `<TextField label="${field.name}" value={${valueExpr}} onChange={${onChangeExpr}} fullWidth size="small" />`;
  }
  if (uiLib === 'antd') {
    return `<Form.Item label="${field.name}"><Input value={${valueExpr}} onChange={${onChangeExpr}} /></Form.Item>`;
  }
  if (uiLib === 'shadcn') {
    return `<div className="space-y-1"><label className="text-sm font-medium">${field.name}</label><Input value={${valueExpr}} onChange={${onChangeExpr}} /></div>`;
  }
  return `<label style={{ display: 'flex', flexDirection: 'column', gap: 4 }}><span style={{ fontSize: 13, fontWeight: 600 }}>${field.name}</span><input value={${valueExpr}} onChange={${onChangeExpr}} style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6 }} /></label>`;
}

function uiButton(uiLib: string, label: string): string {
  if (uiLib === 'mui') return `<Button type="submit" variant="contained">${label}</Button>`;
  if (uiLib === 'antd') return `<Button type="primary" htmlType="submit">${label}</Button>`;
  if (uiLib === 'shadcn') return `<Button type="submit">${label}</Button>`;
  return `<button type="submit" style={{ padding: '10px 20px', background: '#000', color: '#fff', border: 'none', borderRadius: 6, cursor: 'pointer' }}>${label}</button>`;
}

function uiImports(uiLib: string): string {
  if (uiLib === 'mui') return `import { TextField, Button } from '@mui/material';`;
  if (uiLib === 'antd') return `import { Form, Input, Button } from 'antd';`;
  if (uiLib === 'shadcn') return `import { Input } from '@/components/ui/input';\nimport { Button } from '@/components/ui/button';`;
  return '';
}

type AnyField = { name: string; type: string };

function generateCreatePageRHF(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  return `'use client';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
${uiImports(uiLib)}

type FormData = { ${fields.map(f => `${f.name}: string`).join('; ')} };

export default function ${model.name}CreatePage() {
  const router = useRouter();
  const { register, handleSubmit, formState: { errors } } = useForm<FormData>();

  const onSubmit = async (data: FormData) => {
    await fetch('${apiBase}', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
    router.push('/${slug}');
  };

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>New ${model.name}</h1>
      <form onSubmit={handleSubmit(onSubmit)} style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `        <div>
          <label style={{ display: 'block', fontSize: 13, fontWeight: 600, marginBottom: 4 }}>${f.name}</label>
          <input {...register('${f.name}', { required: true })} style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6, width: '100%' }} />
          {errors.${f.name} && <span style={{ color: 'red', fontSize: 12 }}>Required</span>}
        </div>`).join('\n')}
        ${uiButton(uiLib, 'Create')}
      </form>
    </main>
  );
}
`;
}

function generateCreatePageFormik(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  return `'use client';
import { useRouter } from 'next/navigation';
import { Formik, Form, Field, ErrorMessage } from 'formik';
${uiImports(uiLib)}

export default function ${model.name}CreatePage() {
  const router = useRouter();

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>New ${model.name}</h1>
      <Formik
        initialValues={{ ${fields.map(f => `${f.name}: ''`).join(', ')} }}
        onSubmit={async (values) => {
          await fetch('${apiBase}', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) });
          router.push('/${slug}');
        }}
      >
        <Form style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `          <div>
            <label style={{ display: 'block', fontSize: 13, fontWeight: 600, marginBottom: 4 }}>${f.name}</label>
            <Field name="${f.name}" style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6, width: '100%' }} />
            <ErrorMessage name="${f.name}" component="div" />
          </div>`).join('\n')}
          ${uiButton(uiLib, 'Create')}
        </Form>
      </Formik>
    </main>
  );
}
`;
}

function generateCreatePageVanilla(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  return `'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
${uiImports(uiLib)}

export default function ${model.name}CreatePage() {
  const router = useRouter();
  const [form, setForm] = useState({ ${fields.map(f => `${f.name}: ''`).join(', ')} });

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    await fetch('${apiBase}', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
    router.push('/${slug}');
  }

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>New ${model.name}</h1>
      <form onSubmit={handleSubmit} style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `        ${uiInput(uiLib, f, `form.${f.name}`, `e => setForm(p => ({ ...p, ${f.name}: e.target.value }))`)}`).join('\n')}
        ${uiButton(uiLib, 'Create')}
      </form>
    </main>
  );
}
`;
}

function generateEditPageRHF(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  return `'use client';
import { useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import { useForm } from 'react-hook-form';
${uiImports(uiLib)}

type FormData = { ${fields.map(f => `${f.name}: string`).join('; ')} };

export default function ${model.name}EditPage() {
  const router = useRouter();
  const { id } = useParams<{ id: string }>();
  const { register, handleSubmit, reset } = useForm<FormData>();

  useEffect(() => {
    fetch(\`${apiBase}/\${id}\`).then(r => r.json()).then(data => reset(data));
  }, [id, reset]);

  const onSubmit = async (data: FormData) => {
    await fetch(\`${apiBase}/\${id}\`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
    router.push(\`/${slug}/\${id}\`);
  };

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>Edit ${model.name}</h1>
      <form onSubmit={handleSubmit(onSubmit)} style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `        <div>
          <label style={{ display: 'block', fontSize: 13, fontWeight: 600, marginBottom: 4 }}>${f.name}</label>
          <input {...register('${f.name}')} style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6, width: '100%' }} />
        </div>`).join('\n')}
        ${uiButton(uiLib, 'Save')}
      </form>
    </main>
  );
}
`;
}

function generateEditPageFormik(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  return `'use client';
import { useState, useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import { Formik, Form, Field } from 'formik';
${uiImports(uiLib)}

export default function ${model.name}EditPage() {
  const router = useRouter();
  const { id } = useParams<{ id: string }>();
  const [initialValues, setInitialValues] = useState<Record<string, string> | null>(null);

  useEffect(() => {
    fetch(\`${apiBase}/\${id}\`).then(r => r.json()).then(setInitialValues);
  }, [id]);

  if (!initialValues) return <p>Loading...</p>;

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>Edit ${model.name}</h1>
      <Formik
        initialValues={initialValues}
        enableReinitialize
        onSubmit={async (values) => {
          await fetch(\`${apiBase}/\${id}\`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) });
          router.push(\`/${slug}/\${id}\`);
        }}
      >
        <Form style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `          <div>
            <label style={{ display: 'block', fontSize: 13, fontWeight: 600, marginBottom: 4 }}>${f.name}</label>
            <Field name="${f.name}" style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6, width: '100%' }} />
          </div>`).join('\n')}
          ${uiButton(uiLib, 'Save')}
        </Form>
      </Formik>
    </main>
  );
}
`;
}

function generateEditPageVanilla(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  return `'use client';
import { useEffect, useState } from 'react';
import { useRouter, useParams } from 'next/navigation';
${uiImports(uiLib)}

export default function ${model.name}EditPage() {
  const router = useRouter();
  const { id } = useParams<{ id: string }>();
  const [form, setForm] = useState({ ${fields.map(f => `${f.name}: ''`).join(', ')} });

  useEffect(() => {
    fetch(\`${apiBase}/\${id}\`).then(r => r.json()).then(data => setForm(data));
  }, [id]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    await fetch(\`${apiBase}/\${id}\`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
    router.push(\`/${slug}/\${id}\`);
  }

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>Edit ${model.name}</h1>
      <form onSubmit={handleSubmit} style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `        ${uiInput(uiLib, f, `form.${f.name} ?? ''`, `e => setForm(p => ({ ...p, ${f.name}: e.target.value }))`)}`).join('\n')}
        ${uiButton(uiLib, 'Save')}
      </form>
    </main>
  );
}
`;
}

function generateHomePage(models: Model[], projectName: string, opts: ReactOptions): string {
  const uiLib = opts?.ui_lib ?? 'none';
  const useTailwind = opts?.css === 'tailwind' || uiLib === 'shadcn' || uiLib === 'tailwind';
  const links = models.map(m => ({ name: m.name, slug: slugify(m.name) }));

  if (uiLib === 'mui') {
    const items = links.map(({ name, slug }) =>
      `        <Button component="a" href="/${slug}" variant="outlined" sx={{ textTransform: 'none', justifyContent: 'flex-start' }}>${name}</Button>`
    ).join('\n');
    return `import { Container, Typography, Stack, Button } from '@mui/material';

export default function Home() {
  return (
    <Container maxWidth="sm" sx={{ py: 8 }}>
      <Typography variant="h3" gutterBottom>${projectName}</Typography>
      <Typography color="text.secondary" mb={4}>
        Generated by <a href="https://stackinit.dev">Stack-Init</a>. Start building!
      </Typography>
      <Stack spacing={2}>
${items}
      </Stack>
    </Container>
  );
}
`;
  }

  if (uiLib === 'antd') {
    const items = links.map(({ name, slug }) =>
      `        <Button block><a href="/${slug}">${name}</a></Button>`
    ).join('\n');
    return `import { Typography, Space, Button } from 'antd';

export default function Home() {
  return (
    <div style={{ maxWidth: 480, margin: '4rem auto', padding: '0 1rem' }}>
      <Typography.Title>${projectName}</Typography.Title>
      <Typography.Paragraph type="secondary">
        Generated by <a href="https://stackinit.dev">Stack-Init</a>. Start building!
      </Typography.Paragraph>
      <Space direction="vertical" style={{ width: '100%' }}>
${items}
      </Space>
    </div>
  );
}
`;
  }

  if (useTailwind) {
    const items = links.map(({ name, slug }) =>
      `        <a href="/${slug}" className="block px-4 py-3 border rounded-lg hover:bg-gray-50 text-indigo-600 hover:text-indigo-800 no-underline font-medium">${name}</a>`
    ).join('\n');
    return `export default function Home() {
  return (
    <main className="p-8 max-w-lg mx-auto">
      <h1 className="text-3xl font-bold mb-2">${projectName}</h1>
      <p className="text-gray-600 mb-6">
        Generated by <a href="https://stackinit.dev" className="text-indigo-500 hover:underline">Stack-Init</a>. Start building!
      </p>
      <div className="flex flex-col gap-2">
${items}
      </div>
    </main>
  );
}
`;
  }

  // Default: inline styles
  const items = links.map(({ name, slug }) =>
    `        <li><a href="/${slug}" style={{ color: '#6366f1' }}>${name}</a></li>`
  ).join('\n');
  return `export default function Home() {
  return (
    <main style={{ padding: '2rem' }}>
      <h1>${projectName}</h1>
      <p>Generated by <a href="https://stackinit.dev">Stack-Init</a>. Start building!</p>
      <ul style={{ marginTop: '1rem', listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: 8 }}>
${items}
      </ul>
    </main>
  );
}
`;
}

function generatePrismaSeed(models: Model[]): string {
  const seedBlocks = models.map(m => {
    const mLow = m.name.toLowerCase();
    const sampleFields = m.fields
      .filter(f => f.type !== 'id' && f.type !== 'uuid' && f.type !== 'ulid')
      .slice(0, 4)
      .map(f => {
        switch (f.type) {
          case 'boolean': return `    ${f.name}: false,`;
          case 'integer': case 'bigInteger': case 'smallInteger':
          case 'float': case 'double': case 'decimal': return `    ${f.name}: 0,`;
          case 'date': case 'dateTime': case 'timestamp': return `    ${f.name}: new Date(),`;
          case 'enum': return f.values?.length ? `    ${f.name}: '${f.values[0]}',` : `    ${f.name}: '',`;
          default: return `    ${f.name}: 'sample ${f.name}',`;
        }
      })
      .join('\n');
    return `  await prisma.${mLow}.create({\n    data: {\n${sampleFields}\n    },\n  });`;
  }).join('\n\n');

  return `import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
${seedBlocks}
  console.log('Seed complete.');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
`;
}

