import JSZip from 'jszip';
import type { ProjectConfig, Model, ModelPages, ReactOptions } from '@stack-init/schema';
import { slugify, generatePrismaSchema, buildDeps, toTs } from './common';

const DEFAULT_PAGES: ModelPages = { list: true, detail: true, create: true, edit: false };

export async function generateNextjsProject(zip: JSZip, config: ProjectConfig) {
  const { react: reactOpts, models, name: projectName, stack } = config;
  const opts: ReactOptions = reactOpts ?? {} as ReactOptions;
  const isFullStack = stack === 'nextjs' && config.nextjsUsage === 'full-stack';

  // package.json
  const dependencies = buildDeps(opts);
  if (isFullStack) {
    dependencies['@prisma/client'] = '^6.8.0';
  }

  zip.file('package.json', JSON.stringify({
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      ...(isFullStack && {
        "prisma:generate": "prisma generate",
        "prisma:studio": "prisma studio",
        "db:seed": "tsx prisma/seed.ts",
      })
    },
    dependencies,
    devDependencies: {
      typescript: '^5.8.3',
      '@types/node': '^22.15.3',
      '@types/react': '^19.1.0',
      '@types/react-dom': '^19.1.0',
      ...(isFullStack && { prisma: '^6.8.0', tsx: '^4.19.2' })
    },
  }, null, 2));

  // Prisma Schema (if fullstack)
  if (isFullStack) {
    zip.file('prisma/schema.prisma', generatePrismaSchema(config));
    zip.file('prisma/seed.ts', generatePrismaSeed(models));
    zip.file('src/lib/prisma.ts', `import { PrismaClient } from '@prisma/client';

const globalForPrisma = global as unknown as { prisma: PrismaClient };

export const prisma = globalForPrisma.prisma || new PrismaClient();

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;
`);
  }

  // tsconfig.json
  zip.file('tsconfig.json', JSON.stringify({
    compilerOptions: {
      target: 'ES2017',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'react-jsx',
      incremental: true,
      paths: { '@/*': ['./src/*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
    exclude: ['node_modules'],
  }, null, 2));

  // next.config.ts
  zip.file('next.config.ts', `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {};

export default nextConfig;
`);

  // tailwind
  if (opts.css === 'tailwind') {
    zip.file('tailwind.config.ts', `import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
};

export default config;
`);
    zip.file('postcss.config.mjs', `const config = {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};

export default config;
`);
    zip.file('src/app/globals.css', `@import "tailwindcss";
`);
  } else {
    zip.file('src/app/globals.css', `* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: system-ui, sans-serif; }
`);
  }

  // src/app/layout.tsx
  const muiLayout        = opts.ui_lib === 'mui';
  const antdLayout       = opts.ui_lib === 'antd';
  const useQueryProvider = opts.data_fetching === 'tanstack-query';

  const layoutImports = [
    opts.css === 'tailwind' ? "import './globals.css';" : '',
    muiLayout        ? "import { ThemeProvider, createTheme } from '@mui/material/styles';\nimport CssBaseline from '@mui/material/CssBaseline';" : '',
    antdLayout       ? "import { ConfigProvider } from 'antd';" : '',
    useQueryProvider ? "import { Providers } from '@/providers/query-provider';" : '',
  ].filter(Boolean).join('\n');

  const innerContent = muiLayout
    ? `<ThemeProvider theme={createTheme()}><CssBaseline />{children}</ThemeProvider>`
    : antdLayout
    ? `<ConfigProvider>{children}</ConfigProvider>`
    : `{children}`;

  const layoutInner = useQueryProvider
    ? `      <Providers>${innerContent}</Providers>`
    : `      ${innerContent}`;

  zip.file('src/app/layout.tsx', `import type { Metadata } from 'next';
${layoutImports}

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by Stack-Init',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
${layoutInner}
      </body>
    </html>
  );
}
`);

  // src/app/page.tsx
  zip.file('src/app/page.tsx', generateHomePage(models, projectName, opts));

  // State management
  if (opts.state_lib === 'zustand') {
    zip.file('src/stores/useAppStore.ts', `import { create } from 'zustand';

interface AppState {
  counter: number;
  increment: () => void;
  decrement: () => void;
}

export const useAppStore = create<AppState>((set) => ({
  counter: 0,
  increment: () => set((state) => ({ counter: state.counter + 1 })),
  decrement: () => set((state) => ({ counter: state.counter - 1 })),
}));
`);
  }

  if (opts.state_lib === 'redux-toolkit') {
    zip.file('src/store/index.ts', `import { configureStore } from '@reduxjs/toolkit';
import counterReducer from './slices/counterSlice';

export const store = configureStore({
  reducer: {
    counter: counterReducer,
  },
});

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
`);
    zip.file('src/store/hooks.ts', `import { TypedUseSelectorHook, useDispatch, useSelector } from 'react-redux';
import type { RootState, AppDispatch } from '.';

export const useAppDispatch = () => useDispatch<AppDispatch>();
export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector;
`);
    zip.file('src/store/slices/counterSlice.ts', `import { createSlice } from '@reduxjs/toolkit';

interface CounterState { value: number; }
const initialState: CounterState = { value: 0 };

export const counterSlice = createSlice({
  name: 'counter',
  initialState,
  reducers: {
    increment: (state) => { state.value += 1; },
    decrement: (state) => { state.value -= 1; },
  },
});

export const { increment, decrement } = counterSlice.actions;
export default counterSlice.reducer;
`);
  }

  if (opts.state_lib === 'jotai') {
    zip.file('src/atoms/index.ts', `import { atom } from 'jotai';

export const counterAtom = atom(0);
export const loadingAtom = atom(false);
`);
  }

  // HTTP client factory
  zip.file('src/lib/api.ts', generateApiLib(opts.http_lib ?? 'fetch'));

  // Data fetching provider
  if (opts.data_fetching === 'tanstack-query') {
    zip.file('src/providers/query-provider.tsx', generateQueryProvider());
  }

  // Per-model TypeScript interfaces + pages
  for (const model of models) {
    const slug = slugify(model.name);
    const pages: ModelPages = { ...DEFAULT_PAGES, ...model.pages };

    // API Routes (if fullstack)
    if (isFullStack) {
      zip.file(`src/app/api/${slug}/route.ts`, generateApiRoute(model));
      zip.file(`src/app/api/${slug}/[id]/route.ts`, generateApiIdRoute(model));
    }

    // src/types/[ModelName].ts
    const fieldLines = model.fields
      .map((f) => `  ${f.name}${f.nullable ? '?' : ''}: ${f.values?.length ? f.values.map(v => `'${v}'`).join(' | ') : toTs(f.type)};`)
      .join('\n');
    zip.file(`src/types/${model.name}.ts`, `export interface ${model.name} {
  id: number;
${fieldLines}
  created_at: string;
  updated_at: string;
}
`);

    const apiBase = isFullStack ? `/api/${slug}` : `http://localhost:3000/api/${slug}`;

    if (pages.list) {
      zip.file(`src/app/${slug}/page.tsx`, generateListPage(model, apiBase, pages, opts));
    }
    if (pages.detail) {
      zip.file(`src/app/${slug}/[id]/page.tsx`, generateDetailPage(model, apiBase, pages, opts));
    }
    if (pages.create) {
      zip.file(`src/app/${slug}/new/page.tsx`, generateCreatePage(model, apiBase, slug, opts));
    }
    if (pages.edit) {
      zip.file(`src/app/${slug}/[id]/edit/page.tsx`, generateEditPage(model, apiBase, slug, opts));
    }

    // Zod validation schema
    if (opts.form_lib === 'zod') {
      zip.file(`src/schemas/${model.name}.schema.ts`, generateZodSchema(model));
    }

    // Data fetching hooks
    if (opts.data_fetching === 'tanstack-query') {
      zip.file(`src/hooks/use${model.name}.ts`, generateTanstackHook(model, slug));
    } else if (opts.data_fetching === 'swr') {
      zip.file(`src/hooks/use${model.name}.ts`, generateSWRHook(model, slug));
    }
  }
}

function generateApiRoute(model: Model): string {
  return `import { prisma } from '@/lib/prisma';
import { NextResponse } from 'next/server';

export async function GET() {
  const items = await prisma.${model.name.toLowerCase()}.findMany();
  return NextResponse.json(items);
}

export async function POST(req: Request) {
  const data = await req.json();
  const item = await prisma.${model.name.toLowerCase()}.create({ data });
  return NextResponse.json(item);
}
`;
}

function generateApiIdRoute(model: Model): string {
  const mLow = model.name.toLowerCase();
  return `import { prisma } from '@/lib/prisma';
import { NextResponse } from 'next/server';

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const item = await prisma.${mLow}.findUnique({ where: { id: parseInt(id) } });
  return NextResponse.json(item);
}

export async function PATCH(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const data = await req.json();
  const item = await prisma.${mLow}.update({ where: { id: parseInt(id) }, data });
  return NextResponse.json(item);
}

export async function DELETE(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  await prisma.${mLow}.delete({ where: { id: parseInt(id) } });
  return new NextResponse(null, { status: 204 });
}
`;
}

function generateListPage(model: Model, apiBase: string, pages: ModelPages, opts?: ReactOptions | null): string {
  const slug = slugify(model.name);
  const uiLib = opts?.ui_lib ?? 'none';
  const useTailwind = opts?.css === 'tailwind' || uiLib === 'shadcn' || uiLib === 'tailwind';

  const displayFields = model.fields.filter((f: any) => f.type !== 'foreignId').slice(0, 6);

  // Helper: render a cell value expression for the generated JSX
  function cellExpr(f: any): string {
    if (f.type === 'boolean') return `{item.${f.name} ? '✓' : '✗'}`;
    return `{String(item.${f.name} ?? '—')}`;
  }

  if (uiLib === 'mui') {
    const thCells = displayFields.map(f => `            <TableCell><strong>${f.name}</strong></TableCell>`).join('\n');
    const tdCells = displayFields.map(f => `              <TableCell>${cellExpr(f)}</TableCell>`).join('\n');
    const newBtn = pages.create
      ? `<Button component={Link} href="/${slug}/new" variant="contained" size="small">+ New</Button>`
      : '';
    const editCell = pages.edit
      ? `<Button component={Link} href={\`/${slug}/\${item.id}/edit\`} size="small">Edit</Button>`
      : '';
    return `'use client';
import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import { Container, Typography, Stack, Button, Table, TableHead, TableBody, TableRow, TableCell, Alert } from '@mui/material';

export default function ${model.name}ListPage() {
  const [items, setItems]   = useState<any[]>([]);
  const [error, setError]   = useState<string | null>(null);

  const load = useCallback(async () => {
    setError(null);
    try {
      const res = await fetch('${apiBase}');
      if (!res.ok) throw new Error('Failed to fetch');
      setItems(await res.json());
    } catch (e: any) {
      setError(e.message ?? 'Unknown error');
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const handleDelete = async (id: number) => {
    if (!confirm('Delete this item?')) return;
    await fetch(\`${apiBase}/\${id}\`, { method: 'DELETE' });
    setItems(prev => prev.filter((i: any) => i.id !== id));
  };

  return (
    <Container maxWidth="lg" sx={{ py: 4 }}>
      <Stack direction="row" justifyContent="space-between" alignItems="center" mb={3}>
        <Typography variant="h4">${model.name}s</Typography>
        ${newBtn}
      </Stack>
      {error && <Alert severity="error" action={<Button onClick={load} size="small">Retry</Button>} sx={{ mb: 2 }}>{error}</Alert>}
      <Table>
        <TableHead>
          <TableRow>
${thCells}
            <TableCell>Actions</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {items.length === 0 && !error && (
            <TableRow><TableCell colSpan={${displayFields.length + 1}} align="center">No items found.</TableCell></TableRow>
          )}
          {items.map((item: any) => (
            <TableRow key={item.id} hover>
${tdCells}
              <TableCell>
                <Stack direction="row" spacing={1}>
                  ${editCell}
                  <Button onClick={() => handleDelete(item.id)} color="error" size="small">Delete</Button>
                </Stack>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Container>
  );
}
`;
  }

  if (uiLib === 'antd') {
    const columnsArr = displayFields.map(f =>
      f.type === 'boolean'
        ? `  { title: '${f.name}', dataIndex: '${f.name}', key: '${f.name}', render: (v: any) => (v ? '✓' : '✗') }`
        : `  { title: '${f.name}', dataIndex: '${f.name}', key: '${f.name}', render: (v: any) => String(v ?? '—') }`
    ).join(',\n');
    const editAction = pages.edit
      ? `<Link href={\`/${slug}/\${record.id}/edit\`}><Button type="link" size="small">Edit</Button></Link>`
      : '';
    const newBtn = pages.create
      ? `<Link href="/${slug}/new"><Button type="primary">+ New</Button></Link>`
      : '';
    return `'use client';
import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import { Typography, Button, Space, Table, Alert } from 'antd';

const columns = (onDelete: (id: number) => void) => [
${columnsArr},
  {
    title: 'Actions',
    key: 'actions',
    render: (_: any, record: any) => (
      <Space>
        ${editAction}
        <Button danger size="small" onClick={() => { if (confirm('Delete this item?')) onDelete(record.id); }}>Delete</Button>
      </Space>
    ),
  },
];

export default function ${model.name}ListPage() {
  const [items, setItems] = useState<any[]>([]);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setError(null);
    try {
      const res = await fetch('${apiBase}');
      if (!res.ok) throw new Error('Failed to fetch');
      setItems(await res.json());
    } catch (e: any) {
      setError(e.message ?? 'Unknown error');
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const handleDelete = async (id: number) => {
    await fetch(\`${apiBase}/\${id}\`, { method: 'DELETE' });
    setItems(prev => prev.filter((i: any) => i.id !== id));
  };

  return (
    <div style={{ maxWidth: 900, margin: '0 auto', padding: '2rem' }}>
      <Space style={{ width: '100%', justifyContent: 'space-between', marginBottom: 24 }}>
        <Typography.Title level={3} style={{ margin: 0 }}>${model.name}s</Typography.Title>
        ${newBtn}
      </Space>
      {error && <Alert message={error} type="error" showIcon action={<Button onClick={load} size="small">Retry</Button>} style={{ marginBottom: 16 }} />}
      <Table dataSource={items} columns={columns(handleDelete)} rowKey="id" locale={{ emptyText: 'No items found.' }} />
    </div>
  );
}
`;
  }

  if (useTailwind) {
    const thCells = displayFields.map(f => `              <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">${f.name}</th>`).join('\n');
    const tdCells = displayFields.map(f => `              <td className="px-4 py-3 text-sm text-gray-700">${cellExpr(f)}</td>`).join('\n');
    const newLink = pages.create
      ? `<a href="/${slug}/new" className="px-4 py-2 bg-black text-white rounded-md text-sm hover:bg-gray-800 no-underline">+ New</a>`
      : '';
    const editLink = pages.edit
      ? `<a href={\`/${slug}/\${item.id}/edit\`} className="text-sm text-indigo-600 hover:underline">Edit</a>`
      : '';
    return `'use client';
import { useState, useEffect, useCallback } from 'react';

export default function ${model.name}ListPage() {
  const [items, setItems] = useState<any[]>([]);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setError(null);
    try {
      const res = await fetch('${apiBase}');
      if (!res.ok) throw new Error('Failed to fetch');
      setItems(await res.json());
    } catch (e: any) {
      setError(e.message ?? 'Unknown error');
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const handleDelete = async (id: number) => {
    if (!confirm('Delete this item?')) return;
    await fetch(\`${apiBase}/\${id}\`, { method: 'DELETE' });
    setItems(prev => prev.filter((i: any) => i.id !== id));
  };

  return (
    <main className="p-8 max-w-5xl mx-auto">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">${model.name}s</h1>
        ${newLink}
      </div>
      {error && (
        <div className="mb-4 flex items-center gap-3 rounded-md bg-red-50 border border-red-300 px-4 py-3 text-red-700 text-sm">
          <span>{error}</span>
          <button onClick={load} className="ml-auto text-xs underline">Retry</button>
        </div>
      )}
      <div className="overflow-x-auto rounded-lg border border-gray-200">
        <table className="w-full text-left border-collapse">
          <thead className="bg-gray-50">
            <tr>
${thCells}
              <th className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">Actions</th>
            </tr>
          </thead>
          <tbody>
            {items.length === 0 && !error && (
              <tr><td colSpan={${displayFields.length + 1}} className="px-4 py-8 text-center text-gray-400 text-sm">No items found.</td></tr>
            )}
            {items.map((item: any) => (
              <tr key={item.id} className="border-t border-gray-100 hover:bg-gray-50">
${tdCells}
                <td className="px-4 py-3 text-sm flex gap-3 items-center">
                  ${editLink}
                  <button onClick={() => handleDelete(item.id)} className="text-red-600 hover:underline text-sm">Delete</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </main>
  );
}
`;
  }

  // Default: inline styles
  const thCells = displayFields.map(f => `            <th style={{ padding: '10px 16px', background: '#f9fafb', fontWeight: 600, fontSize: 12, color: '#6b7280', textTransform: 'uppercase', textAlign: 'left' }}>${f.name}</th>`).join('\n');
  const tdCells = displayFields.map(f => `            <td style={{ padding: '12px 16px', fontSize: 14 }}>${cellExpr(f)}</td>`).join('\n');
  const newLink = pages.create
    ? `<a href="/${slug}/new" style={{ padding: '8px 16px', background: '#000', color: '#fff', borderRadius: 6, textDecoration: 'none', fontSize: 14 }}>+ New</a>`
    : '';
  const editLink = pages.edit
    ? `<a href={\`/${slug}/\${item.id}/edit\`} style={{ color: '#6366f1', fontSize: 13 }}>Edit</a>`
    : '';
  return `'use client';
import { useState, useEffect, useCallback } from 'react';

export default function ${model.name}ListPage() {
  const [items, setItems] = useState<any[]>([]);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setError(null);
    try {
      const res = await fetch('${apiBase}');
      if (!res.ok) throw new Error('Failed to fetch');
      setItems(await res.json());
    } catch (e: any) {
      setError(e.message ?? 'Unknown error');
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const handleDelete = async (id: number) => {
    if (!confirm('Delete this item?')) return;
    await fetch(\`${apiBase}/\${id}\`, { method: 'DELETE' });
    setItems(prev => prev.filter((i: any) => i.id !== id));
  };

  return (
    <main style={{ padding: '2rem', maxWidth: 900, margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
        <h1 style={{ margin: 0 }}>${model.name}s</h1>
        ${newLink}
      </div>
      {error && (
        <div style={{ marginBottom: 16, display: 'flex', alignItems: 'center', gap: 12, background: '#fef2f2', border: '1px solid #fca5a5', borderRadius: 6, padding: '10px 16px', color: '#dc2626', fontSize: 14 }}>
          <span>{error}</span>
          <button onClick={load} style={{ marginLeft: 'auto', background: 'none', border: 'none', color: '#dc2626', cursor: 'pointer', textDecoration: 'underline', fontSize: 13 }}>Retry</button>
        </div>
      )}
      <div style={{ overflowX: 'auto', borderRadius: 8, border: '1px solid #e5e7eb' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr>
${thCells}
              <th style={{ padding: '10px 16px', background: '#f9fafb', fontWeight: 600, fontSize: 12, color: '#6b7280', textTransform: 'uppercase', textAlign: 'left' }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {items.length === 0 && !error && (
              <tr><td colSpan={${displayFields.length + 1}} style={{ padding: '2rem', textAlign: 'center', color: '#9ca3af', fontSize: 14 }}>No items found.</td></tr>
            )}
            {items.map((item: any) => (
              <tr key={item.id} style={{ borderTop: '1px solid #f3f4f6' }}>
${tdCells}
                <td style={{ padding: '12px 16px', display: 'flex', gap: 12, alignItems: 'center' }}>
                  ${editLink}
                  <button onClick={() => handleDelete(item.id)} style={{ background: 'none', border: 'none', color: '#dc2626', cursor: 'pointer', fontSize: 13, padding: 0 }}>Delete</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </main>
  );
}
`;
}

function generateDetailPage(model: Model, apiBase: string, pages: ModelPages, opts?: ReactOptions | null): string {
  const slug = slugify(model.name);
  const fields = model.fields.slice(0, 6);
  const uiLib = opts?.ui_lib ?? 'none';
  const useTailwind = opts?.css === 'tailwind' || uiLib === 'shadcn' || uiLib === 'tailwind';

  if (uiLib === 'mui') {
    const fieldRows = fields.map(f =>
      `            <Stack direction="row" justifyContent="space-between"><Typography fontWeight={600}>${f.name}</Typography><Typography>{String(item.${f.name} ?? '\u2014')}</Typography></Stack>`
    ).join('\n');
    const editAction = pages.edit
      ? `        <CardActions>\n          <Button component={Link} href={\`/${slug}/\${id}/edit\`} variant="outlined" size="small">Edit</Button>\n        </CardActions>`
      : '';
    return `import Link from 'next/link';
import { Container, Typography, Stack, Card, CardContent, CardActions, Button, Divider } from '@mui/material';

async function getData(id: string) {
  const res = await fetch(\`${apiBase}/\${id}\`, { cache: 'no-store' });
  if (!res.ok) throw new Error('Failed to fetch');
  return res.json();
}

export default async function ${model.name}DetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const item = await getData(id);
  return (
    <Container maxWidth="sm" sx={{ py: 4 }}>
      <Button component={Link} href="/${slug}" size="small" sx={{ mb: 2 }}>&larr; Back</Button>
      <Typography variant="h4" gutterBottom>${model.name} #{'{'}item.id{'}'}</Typography>
      <Card variant="outlined">
        <CardContent>
          <Stack spacing={1} divider={<Divider />}>
${fieldRows}
          </Stack>
        </CardContent>
${editAction}
      </Card>
    </Container>
  );
}
`;
  }

  if (uiLib === 'antd') {
    const descItems = fields.map(f =>
      `            <Descriptions.Item label="${f.name}">{String(item.${f.name} ?? '\u2014')}</Descriptions.Item>`
    ).join('\n');
    const editBtn = pages.edit ? `\n        <Link href={\`/${slug}/\${id}/edit\`}><Button>Edit</Button></Link>` : '';
    return `'use client';
import Link from 'next/link';
import { Typography, Card, Descriptions, Button, Space } from 'antd';
import { useEffect, useState } from 'react';

export default function ${model.name}DetailPage({ params }: { params: { id: string } }) {
  const { id } = params;
  const [item, setItem] = useState<any>(null);

  useEffect(() => {
    fetch(\`${apiBase}/\${id}\`).then(r => r.json()).then(setItem);
  }, [id]);

  if (!item) return <p>Loading...</p>;

  return (
    <div style={{ maxWidth: 600, margin: '0 auto', padding: '2rem' }}>
      <Space direction="vertical" style={{ width: '100%' }}>
        <Link href="/${slug}">&larr; Back</Link>
        <Typography.Title level={3}>${model.name} #{'{'}item.id{'}'}</Typography.Title>
        <Card>
          <Descriptions column={1} bordered>
${descItems}
          </Descriptions>
        </Card>${editBtn}
      </Space>
    </div>
  );
}
`;
  }

  if (useTailwind) {
    const fieldRows = fields.map(f =>
      `        <dt className="font-semibold text-sm">${f.name}</dt><dd className="text-sm">{String(item.${f.name} ?? '\u2014')}</dd>`
    ).join('\n');
    const editLink = pages.edit
      ? `\n        <Link href={\`/${slug}/\${id}/edit\`} className="px-4 py-2 border border-black rounded-md text-sm hover:bg-gray-50 no-underline">Edit</Link>`
      : '';
    return `import Link from 'next/link';

async function getData(id: string) {
  const res = await fetch(\`${apiBase}/\${id}\`, { cache: 'no-store' });
  if (!res.ok) throw new Error('Failed to fetch');
  return res.json();
}

export default async function ${model.name}DetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const item = await getData(id);
  return (
    <main className="p-8 max-w-2xl mx-auto">
      <Link href="/${slug}" className="text-sm text-indigo-500 hover:underline">&larr; Back</Link>
      <h1 className="text-2xl font-bold mt-4 mb-6">${model.name} #{'{'}item.id{'}'}</h1>
      <dl className="grid gap-x-4 gap-y-2" style={{ gridTemplateColumns: '140px 1fr' }}>
${fieldRows}
      </dl>${editLink ? `\n      <div className="mt-6 flex gap-3">${editLink}\n      </div>` : ''}
    </main>
  );
}
`;
  }

  // Default: inline styles
  const fieldRows = fields.map(f =>
    `        <dt style={{ fontWeight: 600 }}>${f.name}</dt><dd>{String(item.${f.name} ?? '\u2014')}</dd>`
  ).join('\n');
  const editLink = pages.edit
    ? `\n        <Link href={\`/${slug}/\${id}/edit\`} style={{ padding: '8px 16px', border: '1px solid #000', borderRadius: 6, textDecoration: 'none' }}>Edit</Link>`
    : '';
  return `import Link from 'next/link';

async function getData(id: string) {
  const res = await fetch(\`${apiBase}/\${id}\`, { cache: 'no-store' });
  if (!res.ok) throw new Error('Failed to fetch');
  return res.json();
}

export default async function ${model.name}DetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const item = await getData(id);
  return (
    <main style={{ padding: '2rem', maxWidth: 600 }}>
      <Link href="/${slug}" style={{ fontSize: 14, color: '#6366f1' }}>&larr; Back</Link>
      <h1 style={{ margin: '1rem 0' }}>${model.name} #{'{'}item.id{'}'}</h1>
      <dl style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: '8px 16px' }}>
${fieldRows}
      </dl>${editLink ? `\n      <div style={{ marginTop: '1.5rem', display: 'flex', gap: 12 }}>${editLink}\n      </div>` : ''}
    </main>
  );
}
`;
}


function generateCreatePage(model: Model, apiBase: string, slug: string, opts?: ReactOptions | null): string {
  const fields = model.fields.filter(f => f.type !== 'foreignId');
  const formLib = opts?.form_lib ?? 'none';
  const uiLib = opts?.ui_lib ?? 'none';

  if (formLib === 'react-hook-form') return generateCreatePageRHF(model, apiBase, slug, uiLib, fields);
  if (formLib === 'formik')          return generateCreatePageFormik(model, apiBase, slug, uiLib, fields);
  if (formLib === 'zod')             return generateCreatePageZod(model, apiBase, slug, uiLib, fields);
  return generateCreatePageVanilla(model, apiBase, slug, uiLib, fields);
}

function generateEditPage(model: Model, apiBase: string, slug: string, opts?: ReactOptions | null): string {
  const fields = model.fields.filter(f => f.type !== 'foreignId');
  const formLib = opts?.form_lib ?? 'none';
  const uiLib = opts?.ui_lib ?? 'none';

  if (formLib === 'react-hook-form') return generateEditPageRHF(model, apiBase, slug, uiLib, fields);
  if (formLib === 'formik')          return generateEditPageFormik(model, apiBase, slug, uiLib, fields);
  if (formLib === 'zod')             return generateEditPageZod(model, apiBase, slug, uiLib, fields);
  return generateEditPageVanilla(model, apiBase, slug, uiLib, fields);
}

function uiInput(uiLib: string, field: any, valueExpr: string, onChangeExpr: string): string {
  const type: string = field.type ?? 'string';
  const name: string = field.name;
  const isBoolean   = type === 'boolean';
  const isEnum      = type === 'enum' && Array.isArray(field.values) && field.values.length > 0;
  const isTextArea  = ['text', 'mediumText', 'longText'].includes(type);
  const isDate      = type === 'date';
  const isDateTime  = ['dateTime', 'timestamp', 'dateTimeTz', 'timestampTz'].includes(type);
  const isNumber    = ['integer','bigInteger','smallInteger','tinyInteger','mediumInteger','unsignedInteger','unsignedBigInteger','float','double','decimal'].includes(type);

  if (uiLib === 'mui') {
    if (isBoolean) {
      return `<FormControlLabel label="${name}" control={<Checkbox checked={!!${valueExpr}} onChange={${onChangeExpr}} />} />`;
    }
    if (isEnum) {
      const options = (field.values as string[]).map(v => `<MenuItem value="${v}">${v}</MenuItem>`).join('');
      return `<FormControl fullWidth size="small"><InputLabel>${name}</InputLabel><Select label="${name}" value={${valueExpr}} onChange={${onChangeExpr}}>${options}</Select></FormControl>`;
    }
    if (isTextArea) {
      return `<TextField label="${name}" value={${valueExpr}} onChange={${onChangeExpr}} fullWidth size="small" multiline rows={3} />`;
    }
    if (isDate) {
      return `<TextField label="${name}" type="date" value={${valueExpr}} onChange={${onChangeExpr}} fullWidth size="small" InputLabelProps={{ shrink: true }} />`;
    }
    if (isDateTime) {
      return `<TextField label="${name}" type="datetime-local" value={${valueExpr}} onChange={${onChangeExpr}} fullWidth size="small" InputLabelProps={{ shrink: true }} />`;
    }
    if (isNumber) {
      return `<TextField label="${name}" type="number" value={${valueExpr}} onChange={${onChangeExpr}} fullWidth size="small" />`;
    }
    return `<TextField label="${name}" value={${valueExpr}} onChange={${onChangeExpr}} fullWidth size="small" />`;
  }

  if (uiLib === 'antd') {
    if (isBoolean) {
      return `<Form.Item label="${name}"><Checkbox checked={!!${valueExpr}} onChange={${onChangeExpr}} /></Form.Item>`;
    }
    if (isEnum) {
      const options = (field.values as string[]).map(v => `{ label: '${v}', value: '${v}' }`).join(', ');
      return `<Form.Item label="${name}"><Select value={${valueExpr}} onChange={${onChangeExpr}} options={[${options}]} style={{ width: '100%' }} /></Form.Item>`;
    }
    if (isTextArea) {
      return `<Form.Item label="${name}"><Input.TextArea value={${valueExpr}} onChange={${onChangeExpr}} rows={3} /></Form.Item>`;
    }
    if (isDate) {
      return `<Form.Item label="${name}"><Input type="date" value={${valueExpr}} onChange={${onChangeExpr}} /></Form.Item>`;
    }
    if (isDateTime) {
      return `<Form.Item label="${name}"><Input type="datetime-local" value={${valueExpr}} onChange={${onChangeExpr}} /></Form.Item>`;
    }
    if (isNumber) {
      return `<Form.Item label="${name}"><InputNumber value={${valueExpr}} onChange={${onChangeExpr}} style={{ width: '100%' }} /></Form.Item>`;
    }
    return `<Form.Item label="${name}"><Input value={${valueExpr}} onChange={${onChangeExpr}} /></Form.Item>`;
  }

  // shadcn / tailwind
  if (uiLib === 'shadcn') {
    if (isBoolean) {
      return `<div className="flex items-center gap-2"><input type="checkbox" id="${name}" checked={!!${valueExpr}} onChange={${onChangeExpr}} className="h-4 w-4" /><label htmlFor="${name}" className="text-sm font-medium">${name}</label></div>`;
    }
    if (isEnum) {
      const options = (field.values as string[]).map(v => `<option value="${v}">${v}</option>`).join('');
      return `<div className="space-y-1"><label className="text-sm font-medium">${name}</label><select value={${valueExpr}} onChange={${onChangeExpr}} className="w-full px-3 py-2 border rounded text-sm">${options}</select></div>`;
    }
    if (isTextArea) {
      return `<div className="space-y-1"><label className="text-sm font-medium">${name}</label><textarea value={${valueExpr}} onChange={${onChangeExpr}} rows={3} className="w-full px-3 py-2 border rounded text-sm" /></div>`;
    }
    if (isDate) {
      return `<div className="space-y-1"><label className="text-sm font-medium">${name}</label><Input type="date" value={${valueExpr}} onChange={${onChangeExpr}} /></div>`;
    }
    if (isDateTime) {
      return `<div className="space-y-1"><label className="text-sm font-medium">${name}</label><Input type="datetime-local" value={${valueExpr}} onChange={${onChangeExpr}} /></div>`;
    }
    if (isNumber) {
      return `<div className="space-y-1"><label className="text-sm font-medium">${name}</label><Input type="number" value={${valueExpr}} onChange={${onChangeExpr}} /></div>`;
    }
    return `<div className="space-y-1"><label className="text-sm font-medium">${name}</label><Input value={${valueExpr}} onChange={${onChangeExpr}} /></div>`;
  }

  // Default: inline styles
  const inputStyle = `style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6, width: '100%' }}`;
  if (isBoolean) {
    return `<label style={{ display: 'flex', alignItems: 'center', gap: 8 }}><input type="checkbox" checked={!!${valueExpr}} onChange={${onChangeExpr}} /><span style={{ fontSize: 13, fontWeight: 600 }}>${name}</span></label>`;
  }
  if (isEnum) {
    const options = (field.values as string[]).map(v => `<option value="${v}">${v}</option>`).join('');
    return `<label style={{ display: 'flex', flexDirection: 'column', gap: 4 }}><span style={{ fontSize: 13, fontWeight: 600 }}>${name}</span><select value={${valueExpr}} onChange={${onChangeExpr}} ${inputStyle}>${options}</select></label>`;
  }
  if (isTextArea) {
    return `<label style={{ display: 'flex', flexDirection: 'column', gap: 4 }}><span style={{ fontSize: 13, fontWeight: 600 }}>${name}</span><textarea value={${valueExpr}} onChange={${onChangeExpr}} rows={3} ${inputStyle} /></label>`;
  }
  if (isDate) {
    return `<label style={{ display: 'flex', flexDirection: 'column', gap: 4 }}><span style={{ fontSize: 13, fontWeight: 600 }}>${name}</span><input type="date" value={${valueExpr}} onChange={${onChangeExpr}} ${inputStyle} /></label>`;
  }
  if (isDateTime) {
    return `<label style={{ display: 'flex', flexDirection: 'column', gap: 4 }}><span style={{ fontSize: 13, fontWeight: 600 }}>${name}</span><input type="datetime-local" value={${valueExpr}} onChange={${onChangeExpr}} ${inputStyle} /></label>`;
  }
  if (isNumber) {
    return `<label style={{ display: 'flex', flexDirection: 'column', gap: 4 }}><span style={{ fontSize: 13, fontWeight: 600 }}>${name}</span><input type="number" value={${valueExpr}} onChange={${onChangeExpr}} ${inputStyle} /></label>`;
  }
  return `<label style={{ display: 'flex', flexDirection: 'column', gap: 4 }}><span style={{ fontSize: 13, fontWeight: 600 }}>${name}</span><input value={${valueExpr}} onChange={${onChangeExpr}} ${inputStyle} /></label>`;
}

function uiButton(uiLib: string, label: string): string {
  if (uiLib === 'mui') return `<Button type="submit" variant="contained">${label}</Button>`;
  if (uiLib === 'antd') return `<Button type="primary" htmlType="submit">${label}</Button>`;
  if (uiLib === 'shadcn') return `<Button type="submit">${label}</Button>`;
  return `<button type="submit" style={{ padding: '10px 20px', background: '#000', color: '#fff', border: 'none', borderRadius: 6, cursor: 'pointer' }}>${label}</button>`;
}

function uiImports(uiLib: string): string {
  if (uiLib === 'mui') return `import { TextField, Button, Checkbox, FormControlLabel, FormControl, InputLabel, Select, MenuItem } from '@mui/material';`;
  if (uiLib === 'antd') return `import { Form, Input, Button, Checkbox, Select, InputNumber } from 'antd';`;
  if (uiLib === 'shadcn') return `import { Input } from '@/components/ui/input';\nimport { Button } from '@/components/ui/button';`;
  return '';
}

type AnyField = { name: string; type: string };

function generateCreatePageRHF(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  return `'use client';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
${uiImports(uiLib)}

type FormData = { ${fields.map(f => `${f.name}: string`).join('; ')} };

export default function ${model.name}CreatePage() {
  const router = useRouter();
  const { register, handleSubmit, formState: { errors } } = useForm<FormData>();

  const onSubmit = async (data: FormData) => {
    await fetch('${apiBase}', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
    router.push('/${slug}');
  };

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>New ${model.name}</h1>
      <form onSubmit={handleSubmit(onSubmit)} style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `        <div>
          <label style={{ display: 'block', fontSize: 13, fontWeight: 600, marginBottom: 4 }}>${f.name}</label>
          <input {...register('${f.name}', { required: true })} style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6, width: '100%' }} />
          {errors.${f.name} && <span style={{ color: 'red', fontSize: 12 }}>Required</span>}
        </div>`).join('\n')}
        ${uiButton(uiLib, 'Create')}
      </form>
    </main>
  );
}
`;
}

function generateCreatePageFormik(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  return `'use client';
import { useRouter } from 'next/navigation';
import { Formik, Form, Field, ErrorMessage } from 'formik';
${uiImports(uiLib)}

export default function ${model.name}CreatePage() {
  const router = useRouter();

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>New ${model.name}</h1>
      <Formik
        initialValues={{ ${fields.map(f => `${f.name}: ''`).join(', ')} }}
        onSubmit={async (values) => {
          await fetch('${apiBase}', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) });
          router.push('/${slug}');
        }}
      >
        <Form style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `          <div>
            <label style={{ display: 'block', fontSize: 13, fontWeight: 600, marginBottom: 4 }}>${f.name}</label>
            <Field name="${f.name}" style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6, width: '100%' }} />
            <ErrorMessage name="${f.name}" component="div" />
          </div>`).join('\n')}
          ${uiButton(uiLib, 'Create')}
        </Form>
      </Formik>
    </main>
  );
}
`;
}

function vanillaOnChange(f: AnyField, antd = false): string {
  const isBoolean = f.type === 'boolean';
  const isNumber  = ['integer','bigInteger','smallInteger','tinyInteger','mediumInteger','unsignedInteger','unsignedBigInteger','float','double','decimal'].includes(f.type);
  const isEnum    = f.type === 'enum';
  if (isBoolean) return `e => setForm(p => ({ ...p, ${f.name}: e.target.checked }))`;
  if (isNumber && !antd) return `e => setForm(p => ({ ...p, ${f.name}: Number(e.target.value) }))`;
  if (isNumber && antd)  return `v => setForm(p => ({ ...p, ${f.name}: Number(v) }))`;
  if (isEnum && antd)    return `v => setForm(p => ({ ...p, ${f.name}: v }))`;
  return `e => setForm(p => ({ ...p, ${f.name}: e.target.value }))`;
}

function vanillaDefaultValue(f: AnyField): string {
  if (f.type === 'boolean') return 'false';
  const isNumber = ['integer','bigInteger','smallInteger','tinyInteger','mediumInteger','unsignedInteger','unsignedBigInteger','float','double','decimal'].includes(f.type);
  if (isNumber) return '0';
  return "''";
}

function generateCreatePageVanilla(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  const antd = uiLib === 'antd';
  return `'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
${uiImports(uiLib)}

export default function ${model.name}CreatePage() {
  const router = useRouter();
  const [form, setForm] = useState({ ${fields.map(f => `${f.name}: ${vanillaDefaultValue(f)}`).join(', ')} });

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    await fetch('${apiBase}', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
    router.push('/${slug}');
  }

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>New ${model.name}</h1>
      <form onSubmit={handleSubmit} style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `        ${uiInput(uiLib, f, `form.${f.name}`, vanillaOnChange(f, antd))}`).join('\n')}
        ${uiButton(uiLib, 'Create')}
      </form>
    </main>
  );
}
`;
}

function generateEditPageRHF(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  return `'use client';
import { useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import { useForm } from 'react-hook-form';
${uiImports(uiLib)}

type FormData = { ${fields.map(f => `${f.name}: string`).join('; ')} };

export default function ${model.name}EditPage() {
  const router = useRouter();
  const { id } = useParams<{ id: string }>();
  const { register, handleSubmit, reset } = useForm<FormData>();

  useEffect(() => {
    fetch(\`${apiBase}/\${id}\`).then(r => r.json()).then(data => reset(data));
  }, [id, reset]);

  const onSubmit = async (data: FormData) => {
    await fetch(\`${apiBase}/\${id}\`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
    router.push(\`/${slug}/\${id}\`);
  };

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>Edit ${model.name}</h1>
      <form onSubmit={handleSubmit(onSubmit)} style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `        <div>
          <label style={{ display: 'block', fontSize: 13, fontWeight: 600, marginBottom: 4 }}>${f.name}</label>
          <input {...register('${f.name}')} style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6, width: '100%' }} />
        </div>`).join('\n')}
        ${uiButton(uiLib, 'Save')}
      </form>
    </main>
  );
}
`;
}

function generateEditPageFormik(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  return `'use client';
import { useState, useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import { Formik, Form, Field } from 'formik';
${uiImports(uiLib)}

export default function ${model.name}EditPage() {
  const router = useRouter();
  const { id } = useParams<{ id: string }>();
  const [initialValues, setInitialValues] = useState<Record<string, string> | null>(null);

  useEffect(() => {
    fetch(\`${apiBase}/\${id}\`).then(r => r.json()).then(setInitialValues);
  }, [id]);

  if (!initialValues) return <p>Loading...</p>;

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>Edit ${model.name}</h1>
      <Formik
        initialValues={initialValues}
        enableReinitialize
        onSubmit={async (values) => {
          await fetch(\`${apiBase}/\${id}\`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) });
          router.push(\`/${slug}/\${id}\`);
        }}
      >
        <Form style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `          <div>
            <label style={{ display: 'block', fontSize: 13, fontWeight: 600, marginBottom: 4 }}>${f.name}</label>
            <Field name="${f.name}" style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6, width: '100%' }} />
          </div>`).join('\n')}
          ${uiButton(uiLib, 'Save')}
        </Form>
      </Formik>
    </main>
  );
}
`;
}

function generateEditPageVanilla(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  const antd = uiLib === 'antd';
  return `'use client';
import { useEffect, useState } from 'react';
import { useRouter, useParams } from 'next/navigation';
${uiImports(uiLib)}

export default function ${model.name}EditPage() {
  const router = useRouter();
  const { id } = useParams<{ id: string }>();
  const [form, setForm] = useState({ ${fields.map(f => `${f.name}: ${vanillaDefaultValue(f)}`).join(', ')} });

  useEffect(() => {
    fetch(\`${apiBase}/\${id}\`).then(r => r.json()).then(data => setForm(data));
  }, [id]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    await fetch(\`${apiBase}/\${id}\`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
    router.push(\`/${slug}/\${id}\`);
  }

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>Edit ${model.name}</h1>
      <form onSubmit={handleSubmit} style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `        ${uiInput(uiLib, f, `form.${f.name}`, vanillaOnChange(f, antd))}`).join('\n')}
        ${uiButton(uiLib, 'Save')}
      </form>
    </main>
  );
}
`;
}

function generateHomePage(models: Model[], projectName: string, opts: ReactOptions): string {
  const uiLib = opts?.ui_lib ?? 'none';
  const useTailwind = opts?.css === 'tailwind' || uiLib === 'shadcn' || uiLib === 'tailwind';
  const links = models.map(m => ({ name: m.name, slug: slugify(m.name) }));

  if (uiLib === 'mui') {
    const items = links.map(({ name, slug }) =>
      `        <Button component="a" href="/${slug}" variant="outlined" sx={{ textTransform: 'none', justifyContent: 'flex-start' }}>${name}</Button>`
    ).join('\n');
    return `import { Container, Typography, Stack, Button } from '@mui/material';

export default function Home() {
  return (
    <Container maxWidth="sm" sx={{ py: 8 }}>
      <Typography variant="h3" gutterBottom>${projectName}</Typography>
      <Typography color="text.secondary" mb={4}>
        Generated by <a href="https://stackinit.dev">Stack-Init</a>. Start building!
      </Typography>
      <Stack spacing={2}>
${items}
      </Stack>
    </Container>
  );
}
`;
  }

  if (uiLib === 'antd') {
    const items = links.map(({ name, slug }) =>
      `        <Button block><a href="/${slug}">${name}</a></Button>`
    ).join('\n');
    return `import { Typography, Space, Button } from 'antd';

export default function Home() {
  return (
    <div style={{ maxWidth: 480, margin: '4rem auto', padding: '0 1rem' }}>
      <Typography.Title>${projectName}</Typography.Title>
      <Typography.Paragraph type="secondary">
        Generated by <a href="https://stackinit.dev">Stack-Init</a>. Start building!
      </Typography.Paragraph>
      <Space direction="vertical" style={{ width: '100%' }}>
${items}
      </Space>
    </div>
  );
}
`;
  }

  if (useTailwind) {
    const items = links.map(({ name, slug }) =>
      `        <a href="/${slug}" className="block px-4 py-3 border rounded-lg hover:bg-gray-50 text-indigo-600 hover:text-indigo-800 no-underline font-medium">${name}</a>`
    ).join('\n');
    return `export default function Home() {
  return (
    <main className="p-8 max-w-lg mx-auto">
      <h1 className="text-3xl font-bold mb-2">${projectName}</h1>
      <p className="text-gray-600 mb-6">
        Generated by <a href="https://stackinit.dev" className="text-indigo-500 hover:underline">Stack-Init</a>. Start building!
      </p>
      <div className="flex flex-col gap-2">
${items}
      </div>
    </main>
  );
}
`;
  }

  // Default: inline styles
  const items = links.map(({ name, slug }) =>
    `        <li><a href="/${slug}" style={{ color: '#6366f1' }}>${name}</a></li>`
  ).join('\n');
  return `export default function Home() {
  return (
    <main style={{ padding: '2rem' }}>
      <h1>${projectName}</h1>
      <p>Generated by <a href="https://stackinit.dev">Stack-Init</a>. Start building!</p>
      <ul style={{ marginTop: '1rem', listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: 8 }}>
${items}
      </ul>
    </main>
  );
}
`;
}

// ─── HTTP client factory ──────────────────────────────────────────────────────

function generateApiLib(httpLib: string): string {
  if (httpLib === 'axios') {
    return `import axios from 'axios';

export function createApi<T>(resource: string) {
  const base = \`/api/\${resource}\`;
  return {
    list:   ()                                       => axios.get<T[]>(base).then(r => r.data),
    get:    (id: number | string)                    => axios.get<T>(\`\${base}/\${id}\`).then(r => r.data),
    create: (data: Partial<T>)                       => axios.post<T>(base, data).then(r => r.data),
    update: (id: number | string, data: Partial<T>) => axios.patch<T>(\`\${base}/\${id}\`, data).then(r => r.data),
    remove: (id: number | string)                    => axios.delete(\`\${base}/\${id}\`),
  };
}
`;
  }
  if (httpLib === 'ky') {
    return `import ky from 'ky';

export function createApi<T>(resource: string) {
  const base = \`/api/\${resource}\`;
  return {
    list:   ()                                       => ky.get(base).json<T[]>(),
    get:    (id: number | string)                    => ky.get(\`\${base}/\${id}\`).json<T>(),
    create: (data: Partial<T>)                       => ky.post(base, { json: data }).json<T>(),
    update: (id: number | string, data: Partial<T>) => ky.patch(\`\${base}/\${id}\`, { json: data }).json<T>(),
    remove: (id: number | string)                    => ky.delete(\`\${base}/\${id}\`),
  };
}
`;
  }
  return `export function createApi<T>(resource: string) {
  const base = \`/api/\${resource}\`;
  async function req<R>(url: string, init?: RequestInit): Promise<R> {
    const res = await fetch(url, init);
    if (!res.ok) throw new Error(\`API error \${res.status}\`);
    if (res.status === 204) return undefined as R;
    return res.json() as Promise<R>;
  }
  return {
    list:   ()                                       => req<T[]>(base),
    get:    (id: number | string)                    => req<T>(\`\${base}/\${id}\`),
    create: (data: Partial<T>)                       => req<T>(base, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }),
    update: (id: number | string, data: Partial<T>) => req<T>(\`\${base}/\${id}\`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }),
    remove: (id: number | string)                    => req<void>(\`\${base}/\${id}\`, { method: 'DELETE' }),
  };
}
`;
}

// ─── TanStack Query provider ─────────────────────────────────────────────────

function generateQueryProvider(): string {
  return `'use client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { useState } from 'react';

export function Providers({ children }: { children: React.ReactNode }) {
  const [queryClient] = useState(() => new QueryClient());
  return <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>;
}
`;
}

// ─── Zod schema ──────────────────────────────────────────────────────────────

function toZodType(f: { type: string; nullable?: boolean; values?: string[] }): string {
  const optional = f.nullable ? '.optional()' : '';
  let base: string;
  switch (f.type) {
    case 'integer': case 'bigInteger': case 'smallInteger': case 'mediumInteger':
    case 'unsignedInteger': case 'unsignedBigInteger': case 'float': case 'double': case 'decimal':
    case 'foreignId':
      base = 'z.coerce.number()'; break;
    case 'boolean':
      base = 'z.boolean()'; break;
    case 'enum':
      base = f.values?.length ? `z.enum([${f.values.map(v => `'${v}'`).join(', ')}])` : 'z.string()'; break;
    default:
      base = f.nullable ? 'z.string()' : 'z.string().min(1)';
  }
  return `${base}${optional}`;
}

function generateZodSchema(model: Model): string {
  const fields = model.fields.filter(f => f.type !== 'foreignId');
  const lines = fields.map(f => `  ${f.name}: ${toZodType(f)},`);
  return `import { z } from 'zod';

export const ${model.name}Schema = z.object({
${lines.join('\n')}
});

export type ${model.name}FormData = z.infer<typeof ${model.name}Schema>;
`;
}

// ─── Zod create/edit pages ───────────────────────────────────────────────────

function generateCreatePageZod(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  return `'use client';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { ${model.name}Schema, type ${model.name}FormData } from '@/schemas/${model.name}.schema';
${uiImports(uiLib)}

export default function ${model.name}CreatePage() {
  const router = useRouter();
  const { register, handleSubmit, formState: { errors } } = useForm<${model.name}FormData>({
    resolver: zodResolver(${model.name}Schema),
  });

  const onSubmit = async (data: ${model.name}FormData) => {
    await fetch('${apiBase}', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
    router.push('/${slug}');
  };

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>New ${model.name}</h1>
      <form onSubmit={handleSubmit(onSubmit)} style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `        <div>
          <label style={{ display: 'block', fontSize: 13, fontWeight: 600, marginBottom: 4 }}>${f.name}</label>
          <input {...register('${f.name}')} style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6, width: '100%' }} />
          {errors.${f.name} && <span style={{ color: 'red', fontSize: 12 }}>{errors.${f.name}?.message}</span>}
        </div>`).join('\n')}
        ${uiButton(uiLib, 'Create')}
      </form>
    </main>
  );
}
`;
}

function generateEditPageZod(model: Model, apiBase: string, slug: string, uiLib: string, fields: AnyField[]): string {
  return `'use client';
import { useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { ${model.name}Schema, type ${model.name}FormData } from '@/schemas/${model.name}.schema';
${uiImports(uiLib)}

export default function ${model.name}EditPage() {
  const router = useRouter();
  const { id } = useParams<{ id: string }>();
  const { register, handleSubmit, reset, formState: { errors } } = useForm<${model.name}FormData>({
    resolver: zodResolver(${model.name}Schema),
  });

  useEffect(() => {
    fetch(\`${apiBase}/\${id}\`).then(r => r.json()).then(data => reset(data));
  }, [id, reset]);

  const onSubmit = async (data: ${model.name}FormData) => {
    await fetch(\`${apiBase}/\${id}\`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
    router.push(\`/${slug}/\${id}\`);
  };

  return (
    <main style={{ padding: '2rem', maxWidth: 480 }}>
      <h1>Edit ${model.name}</h1>
      <form onSubmit={handleSubmit(onSubmit)} style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: 16 }}>
${fields.map(f => `        <div>
          <label style={{ display: 'block', fontSize: 13, fontWeight: 600, marginBottom: 4 }}>${f.name}</label>
          <input {...register('${f.name}')} style={{ padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: 6, width: '100%' }} />
          {errors.${f.name} && <span style={{ color: 'red', fontSize: 12 }}>{errors.${f.name}?.message}</span>}
        </div>`).join('\n')}
        ${uiButton(uiLib, 'Save')}
      </form>
    </main>
  );
}
`;
}

// ─── Data-fetching hooks ──────────────────────────────────────────────────────

function generateTanstackHook(model: Model, slug: string): string {
  const Name = model.name;
  return `'use client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { createApi } from '@/lib/api';
import type { ${Name} } from '@/types/${Name}';

const api = createApi<${Name}>('${slug}');

export function use${Name}List() {
  return useQuery({ queryKey: ['${slug}'], queryFn: () => api.list() });
}

export function use${Name}(id: number) {
  return useQuery({ queryKey: ['${slug}', id], queryFn: () => api.get(id), enabled: !!id });
}

export function useCreate${Name}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: Partial<${Name}>) => api.create(data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['${slug}'] }),
  });
}

export function useUpdate${Name}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: Partial<${Name}> }) => api.update(id, data),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['${slug}'] }),
  });
}

export function useDelete${Name}() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: number) => api.remove(id),
    onSuccess: () => qc.invalidateQueries({ queryKey: ['${slug}'] }),
  });
}
`;
}

function generateSWRHook(model: Model, slug: string): string {
  const Name = model.name;
  return `'use client';
import useSWR from 'swr';
import { createApi } from '@/lib/api';
import type { ${Name} } from '@/types/${Name}';

const api = createApi<${Name}>('${slug}');

export function use${Name}List() {
  return useSWR('${slug}', () => api.list());
}

export function use${Name}(id: number) {
  return useSWR(id ? ['${slug}', id] : null, () => api.get(id));
}
`;
}

function generatePrismaSeed(models: Model[]): string {
  const seedBlocks = models.map(m => {
    const mLow = m.name.toLowerCase();
    const sampleFields = m.fields
      .filter(f => f.type !== 'id' && f.type !== 'uuid' && f.type !== 'ulid')
      .slice(0, 4)
      .map(f => {
        switch (f.type) {
          case 'boolean': return `    ${f.name}: false,`;
          case 'integer': case 'bigInteger': case 'smallInteger':
          case 'float': case 'double': case 'decimal': return `    ${f.name}: 0,`;
          case 'date': case 'dateTime': case 'timestamp': return `    ${f.name}: new Date(),`;
          case 'enum': return f.values?.length ? `    ${f.name}: '${f.values[0]}',` : `    ${f.name}: '',`;
          default: return `    ${f.name}: 'sample ${f.name}',`;
        }
      })
      .join('\n');
    return `  await prisma.${mLow}.create({\n    data: {\n${sampleFields}\n    },\n  });`;
  }).join('\n\n');

  return `import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
${seedBlocks}
  console.log('Seed complete.');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
`;
}

