import JSZip from 'jszip';
import type { ProjectConfig, Model, NamedField } from '@stack-init/schema';
import { toPrismaType } from './common';

function toKebab(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

function toCamel(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

export async function generateT3Project(zip: JSZip, config: ProjectConfig): Promise<void> {
  const { models, name: projectName } = config;

  // package.json
  zip.file('package.json', JSON.stringify({
    name: projectName.toLowerCase().replace(/\s+/g, '-'),
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      'db:generate': 'prisma generate',
      'db:push': 'prisma db push',
      'db:studio': 'prisma studio',
    },
    dependencies: {
      next:                    '^15.3.1',
      react:                   '^19.1.0',
      'react-dom':             '^19.1.0',
      '@prisma/client':        '^6.8.0',
      '@trpc/server':          '^11.1.0',
      '@trpc/client':          '^11.1.0',
      '@trpc/react-query':     '^11.1.0',
      '@tanstack/react-query': '^5.65.0',
      superjson:               '^2.2.1',
      zod:                     '^3.23.4',
      tailwindcss:             '^4.1.5',
      '@tailwindcss/postcss':  '^4.1.5',
    },
    devDependencies: {
      typescript:         '^5.8.3',
      '@types/node':      '^22.15.3',
      '@types/react':     '^19.1.0',
      '@types/react-dom': '^19.1.0',
      prisma:             '^6.8.0',
    },
  }, null, 2));

  // tsconfig.json
  zip.file('tsconfig.json', JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      paths: { '~/*': ['./src/*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  }, null, 2));

  // next.config.ts
  zip.file('next.config.ts', `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  typescript: { ignoreBuildErrors: false },
  eslint: { ignoreDuringBuilds: false },
};

export default nextConfig;
`);

  // tailwind.config.ts
  zip.file('tailwind.config.ts', `import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
};

export default config;
`);

  // postcss.config.mjs
  zip.file('postcss.config.mjs', `const config = { plugins: { '@tailwindcss/postcss': {} } };\nexport default config;\n`);

  // .env
  zip.file('.env', `DATABASE_URL="postgresql://user:password@localhost:5432/${projectName}?schema=public"\nNEXTAUTH_SECRET="your-secret-here"\nNEXTAUTH_URL="http://localhost:3000"\n`);

  // .gitignore
  zip.file('.gitignore', `node_modules\n.next\ndist\n.env\n*.log\n`);

  // prisma/schema.prisma
  zip.file('prisma/schema.prisma', buildPrismaSchema(models));

  // src/app/globals.css
  zip.file('src/app/globals.css', `@import "tailwindcss";\n`);

  // src/app/layout.tsx
  zip.file('src/app/layout.tsx', `import type { Metadata } from 'next';
import './globals.css';
import { TRPCReactProvider } from '~/trpc/react';

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by Stack-Init — T3 Stack',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
`);

  // src/app/page.tsx
  const links = models.map(m => {
    const slug = toKebab(m.name);
    return `        <a href="/${slug}" className="block px-4 py-3 border rounded-lg hover:bg-gray-50 text-indigo-600 font-medium no-underline">${m.name}s</a>`;
  }).join('\n');

  zip.file('src/app/page.tsx', `export default function Home() {
  return (
    <main className="p-8 max-w-lg mx-auto">
      <h1 className="text-3xl font-bold mb-2">${projectName}</h1>
      <p className="text-gray-600 mb-6">
        Powered by{' '}
        <a href="https://create.t3.gg" className="text-indigo-500 hover:underline">T3 Stack</a>
        {' '}— Generated by Stack-Init
      </p>
      <div className="flex flex-col gap-2">
${links}
      </div>
    </main>
  );
}
`);

  // src/server/db.ts
  zip.file('src/server/db.ts', `import { PrismaClient } from '@prisma/client';

const createPrismaClient = () =>
  new PrismaClient({
    log: process.env.NODE_ENV === 'development' ? ['query', 'error', 'warn'] : ['error'],
  });

const globalForPrisma = globalThis as unknown as {
  prisma: ReturnType<typeof createPrismaClient> | undefined;
};

export const db = globalForPrisma.prisma ?? createPrismaClient();

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = db;
`);

  // src/server/api/trpc.ts
  zip.file('src/server/api/trpc.ts', `import { initTRPC } from '@trpc/server';
import superjson from 'superjson';
import { ZodError } from 'zod';
import { db } from '~/server/db';

export const createTRPCContext = async (opts: { headers: Headers }) => ({
  db,
  headers: opts.headers,
});

type Context = Awaited<ReturnType<typeof createTRPCContext>>;

const t = initTRPC.context<Context>().create({
  transformer: superjson,
  errorFormatter({ shape, error }) {
    return {
      ...shape,
      data: {
        ...shape.data,
        zodError: error.cause instanceof ZodError ? error.cause.flatten() : null,
      },
    };
  },
});

export const createCallerFactory = t.createCallerFactory;
export const createTRPCRouter   = t.router;
export const publicProcedure    = t.procedure;
`);

  // src/server/api/root.ts
  const routerImports = models.map(m => `import { ${toCamel(m.name)}Router } from './routers/${toKebab(m.name)}';`).join('\n');
  const routerMap     = models.map(m => `  ${toCamel(m.name)}: ${toCamel(m.name)}Router,`).join('\n');
  zip.file('src/server/api/root.ts', `import { createCallerFactory, createTRPCRouter } from '~/server/api/trpc';
${routerImports}

export const appRouter = createTRPCRouter({
${routerMap}
});

export type AppRouter = typeof appRouter;
export const createCaller = createCallerFactory(appRouter);
`);

  // src/trpc/query-client.ts
  zip.file('src/trpc/query-client.ts', `import { defaultShouldDehydrateQuery, QueryClient } from '@tanstack/react-query';
import superjson from 'superjson';

export function createQueryClient() {
  return new QueryClient({
    defaultOptions: {
      queries: { staleTime: 30 * 1000 },
      dehydrate: {
        serializeData: superjson.serialize,
        shouldDehydrateQuery: (q) =>
          defaultShouldDehydrateQuery(q) || q.state.status === 'pending',
      },
      hydrate: { deserializeData: superjson.deserialize },
    },
  });
}
`);

  // src/trpc/react.tsx
  zip.file('src/trpc/react.tsx', `'use client';

import { type QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { loggerLink, unstable_httpBatchStreamLink } from '@trpc/client';
import { createTRPCReact } from '@trpc/react-query';
import { type inferRouterInputs, type inferRouterOutputs } from '@trpc/server';
import { useState } from 'react';
import superjson from 'superjson';
import { type AppRouter } from '~/server/api/root';
import { createQueryClient } from './query-client';

let clientQueryClientSingleton: QueryClient | undefined;
const getQueryClient = () => {
  if (typeof window === 'undefined') return createQueryClient();
  return (clientQueryClientSingleton ??= createQueryClient());
};

export const api = createTRPCReact<AppRouter>();
export type RouterInputs  = inferRouterInputs<AppRouter>;
export type RouterOutputs = inferRouterOutputs<AppRouter>;

export function TRPCReactProvider({ children }: { children: React.ReactNode }) {
  const queryClient = getQueryClient();
  const [trpcClient] = useState(() =>
    api.createClient({
      links: [
        loggerLink({ enabled: (op) => process.env.NODE_ENV === 'development' || (op.direction === 'down' && op.result instanceof Error) }),
        unstable_httpBatchStreamLink({
          transformer: superjson,
          url: \`\${getBaseUrl()}/api/trpc\`,
          headers() {
            const h = new Headers();
            h.set('x-trpc-source', 'nextjs-react');
            return h;
          },
        }),
      ],
    })
  );
  return (
    <QueryClientProvider client={queryClient}>
      <api.Provider client={trpcClient} queryClient={queryClient}>
        {children}
      </api.Provider>
    </QueryClientProvider>
  );
}

function getBaseUrl() {
  if (typeof window !== 'undefined') return window.location.origin;
  if (process.env.VERCEL_URL) return \`https://\${process.env.VERCEL_URL}\`;
  return \`http://localhost:\${process.env.PORT ?? 3000}\`;
}
`);

  // src/trpc/server.ts
  zip.file('src/trpc/server.ts', `import 'server-only';
import { createHydrationHelpers } from '@trpc/react-query/rsc';
import { headers } from 'next/headers';
import { cache } from 'react';
import { createCaller, type AppRouter } from '~/server/api/root';
import { createTRPCContext } from '~/server/api/trpc';
import { createQueryClient } from './query-client';

const createContext = cache(async () => {
  const h = await headers();
  return createTRPCContext({ headers: h });
});

const getQueryClient = cache(createQueryClient);
const caller = createCaller(createContext);

export const { trpc: api, HydrateClient } = createHydrationHelpers<AppRouter>(caller, getQueryClient);
`);

  // src/app/api/trpc/[trpc]/route.ts
  zip.file('src/app/api/trpc/[trpc]/route.ts', `import { fetchRequestHandler } from '@trpc/server/adapters/fetch';
import { type NextRequest } from 'next/server';
import { appRouter } from '~/server/api/root';
import { createTRPCContext } from '~/server/api/trpc';

const handler = (req: NextRequest) =>
  fetchRequestHandler({
    endpoint: '/api/trpc',
    req,
    router: appRouter,
    createContext: () => createTRPCContext({ headers: req.headers }),
    onError:
      process.env.NODE_ENV === 'development'
        ? ({ path, error }) => console.error(\`❌ tRPC failed on \${path ?? '<no-path>'}: \${error.message}\`)
        : undefined,
  });

export { handler as GET, handler as POST };
`);

  // Per-model files
  for (const model of models) {
    const slug   = toKebab(model.name);
    const mCamel = toCamel(model.name);
    const mLow   = model.name.toLowerCase();

    zip.file(`src/server/api/routers/${slug}.ts`, buildRouter(model, mLow, mCamel));
    zip.file(`src/app/${slug}/page.tsx`, buildListPage(model, slug, mCamel));
    zip.file(`src/app/${slug}/new/page.tsx`, buildCreatePage(model, slug, mCamel));
    zip.file(`src/app/${slug}/[id]/edit/page.tsx`, buildEditPage(model, slug, mCamel));
  }
}

// ─── helpers ──────────────────────────────────────────────────────────────────

function buildPrismaSchema(models: Model[]): string {
  let schema = `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;
  for (const model of models) {
    schema += `model ${model.name} {\n`;
    schema += `  id        Int      @id @default(autoincrement())\n`;
    for (const field of model.fields as NamedField[]) {
      if (['id', 'uuid', 'ulid'].includes(field.type)) continue;
      const pType    = toPrismaType(field.type);
      const nullable = 'nullable' in field && field.nullable ? '?' : '';
      const unique   = 'unique'   in field && field.unique   ? ' @unique' : '';
      schema += `  ${field.name} ${pType}${nullable}${unique}\n`;
    }
    schema += `  createdAt DateTime @default(now())\n`;
    schema += `  updatedAt DateTime @updatedAt\n`;
    if (model.table) schema += `\n  @@map("${model.table}")\n`;
    schema += `}\n\n`;
  }
  return schema;
}

function buildRouter(model: Model, mLow: string, mCamel: string): string {
  const fields = (model.fields as NamedField[]).filter(f => !['id', 'uuid', 'ulid'].includes(f.type));
  const inputFields = fields.slice(0, 8).map(f => {
    const nullable = 'nullable' in f && f.nullable;
    switch (f.type) {
      case 'integer': case 'smallInteger': case 'mediumInteger': case 'bigInteger':
      case 'float': case 'double': case 'decimal': case 'foreignId':
        return `    ${f.name}: z.number()${nullable ? '.optional()' : ''},`;
      case 'boolean':
        return `    ${f.name}: z.boolean()${nullable ? '.optional()' : ''},`;
      default:
        return `    ${f.name}: z.string()${nullable ? '.optional()' : ''},`;
    }
  }).join('\n');

  return `import { z } from 'zod';
import { createTRPCRouter, publicProcedure } from '~/server/api/trpc';

export const ${mCamel}Router = createTRPCRouter({
  getAll: publicProcedure.query(async ({ ctx }) => {
    return ctx.db.${mLow}.findMany({ orderBy: { createdAt: 'desc' } });
  }),

  getById: publicProcedure
    .input(z.object({ id: z.number() }))
    .query(async ({ ctx, input }) => {
      return ctx.db.${mLow}.findUnique({ where: { id: input.id } });
    }),

  create: publicProcedure
    .input(z.object({
${inputFields}
    }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.${mLow}.create({ data: input });
    }),

  update: publicProcedure
    .input(z.object({ id: z.number(),
${inputFields.replace(/,$/mg, '.optional(),')}
    }))
    .mutation(async ({ ctx, input }) => {
      const { id, ...data } = input;
      return ctx.db.${mLow}.update({ where: { id }, data });
    }),

  delete: publicProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ ctx, input }) => {
      return ctx.db.${mLow}.delete({ where: { id: input.id } });
    }),
});
`;
}

function stateInitValue(f: NamedField): string {
  switch (f.type) {
    case 'boolean': return 'false';
    case 'integer': case 'smallInteger': case 'mediumInteger': case 'bigInteger':
    case 'float': case 'double': case 'decimal': case 'foreignId':
      return '0';
    default: {
      const vals: string[] = (f as any).values ?? [];
      return vals.length > 0 ? "'" + vals[0] + "'" : "''";
    }
  }
}

function buildFieldInput(f: NamedField): string {
  const cls = 'w-full border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400';
  const vals: string[] = (f as any).values ?? [];

  if (f.type === 'boolean') {
    return `          <div className="flex items-center gap-2">
            <input type="checkbox" id="${f.name}"
              checked={form.${f.name} as boolean}
              onChange={e => setForm(p => ({ ...p, ${f.name}: e.target.checked }))}
              className="h-4 w-4 rounded border-gray-300 text-indigo-600" />
            <label htmlFor="${f.name}" className="text-sm font-medium">${f.name}</label>
          </div>`;
  }
  if (['integer','smallInteger','mediumInteger','bigInteger','float','double','decimal','foreignId'].includes(f.type)) {
    return `          <div>
            <label className="block text-sm font-medium mb-1">${f.name}</label>
            <input type="number" className="${cls}"
              value={form.${f.name} as number}
              onChange={e => setForm(p => ({ ...p, ${f.name}: Number(e.target.value) }))}
            />
          </div>`;
  }
  if (f.type === 'date') {
    return `          <div>
            <label className="block text-sm font-medium mb-1">${f.name}</label>
            <input type="date" className="${cls}"
              value={form.${f.name} as string}
              onChange={e => setForm(p => ({ ...p, ${f.name}: e.target.value }))}
            />
          </div>`;
  }
  if (f.type === 'dateTime' || f.type === 'timestamp') {
    return `          <div>
            <label className="block text-sm font-medium mb-1">${f.name}</label>
            <input type="datetime-local" className="${cls}"
              value={form.${f.name} as string}
              onChange={e => setForm(p => ({ ...p, ${f.name}: e.target.value }))}
            />
          </div>`;
  }
  if (f.type === 'text' || f.type === 'mediumText' || f.type === 'longText') {
    return `          <div>
            <label className="block text-sm font-medium mb-1">${f.name}</label>
            <textarea rows={4} className="${cls}"
              value={form.${f.name} as string}
              onChange={e => setForm(p => ({ ...p, ${f.name}: e.target.value }))}
            />
          </div>`;
  }
  if (vals.length > 0) {
    const options = vals.map((v: string) => `              <option value="${v}">${v}</option>`).join('\n');
    return `          <div>
            <label className="block text-sm font-medium mb-1">${f.name}</label>
            <select className="${cls}"
              value={form.${f.name} as string}
              onChange={e => setForm(p => ({ ...p, ${f.name}: e.target.value }))}
            >
${options}
            </select>
          </div>`;
  }
  return `          <div>
            <label className="block text-sm font-medium mb-1">${f.name}</label>
            <input type="text" className="${cls}"
              value={form.${f.name} as string}
              onChange={e => setForm(p => ({ ...p, ${f.name}: e.target.value }))}
            />
          </div>`;
}

function buildListPage(model: Model, slug: string, mCamel: string): string {
  const Name = model.name;
  const displayFields = (model.fields as NamedField[])
    .filter(f => !['id', 'uuid', 'ulid', 'foreignId'].includes(f.type))
    .slice(0, 6);

  const headers = displayFields.map(f =>
    `            <th className="text-left py-3 px-4 text-xs font-semibold text-gray-500 uppercase tracking-wide">${f.name}</th>`
  ).join('\n');

  const cells = displayFields.map(f => {
    if (f.type === 'boolean') {
      return `              <td className="py-3 px-4">{item.${f.name} ? '✓' : '✗'}</td>`;
    }
    return `              <td className="py-3 px-4 text-gray-700">{String(item.${f.name} ?? '—')}</td>`;
  }).join('\n');

  return `'use client';
import Link from 'next/link';
import { api } from '~/trpc/react';

export default function ${Name}ListPage() {
  const query = api.${mCamel}.getAll.useQuery();
  const { data: items = [], isLoading } = query;
  const utils = api.useUtils();
  const del = api.${mCamel}.delete.useMutation({
    onSuccess: () => utils.${mCamel}.getAll.invalidate(),
  });

  if (isLoading) return <p className="p-8 text-gray-500">Loading…</p>;

  return (
    <main className="p-8 max-w-5xl mx-auto">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">${Name}s</h1>
        <Link href="/${slug}/new" className="px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm hover:bg-indigo-700 no-underline">
          + New
        </Link>
      </div>
      {query.isError && (
        <div className="mb-4 flex items-center gap-3 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          <span>{query.error?.message}</span>
          <button onClick={() => query.refetch()} className="ml-auto underline hover:no-underline">Retry</button>
        </div>
      )}
      {!query.isError && items.length === 0 && (
        <p className="text-gray-400 text-sm">No ${model.name.toLowerCase()}s yet.</p>
      )}
      {!query.isError && items.length > 0 && (
        <div className="overflow-x-auto rounded-lg border">
          <table className="min-w-full text-sm">
            <thead className="bg-gray-50 border-b">
              <tr>
${headers}
                <th className="py-3 px-4 text-right text-xs font-semibold text-gray-500 uppercase tracking-wide">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {items.map((item) => (
                <tr key={item.id} className="hover:bg-gray-50">
${cells}
                  <td className="py-3 px-4 text-right">
                    <div className="flex justify-end gap-3">
                      <Link href={\`/${slug}/\${item.id}/edit\`} className="text-xs text-indigo-500 hover:underline">Edit</Link>
                      <button
                        onClick={() => { if (window.confirm('Delete this ${model.name.toLowerCase()}?')) del.mutate({ id: item.id }); }}
                        className="text-xs text-red-500 hover:underline"
                      >Delete</button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </main>
  );
}
`;
}

function buildCreatePage(model: Model, slug: string, mCamel: string): string {
  const Name   = model.name;
  const fields = (model.fields as NamedField[]).filter(f => !['id', 'uuid', 'ulid'].includes(f.type)).slice(0, 10);
  const stateInit = fields.map(f => `${f.name}: ${stateInitValue(f)}`).join(', ');
  const inputs    = fields.map(f => buildFieldInput(f)).join('\n');

  return `'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { api } from '~/trpc/react';

export default function ${Name}CreatePage() {
  const router = useRouter();
  const [form, setForm] = useState({ ${stateInit} });
  const utils = api.useUtils();
  const create = api.${mCamel}.create.useMutation({
    onSuccess: () => { utils.${mCamel}.getAll.invalidate(); router.push('/${slug}'); },
  });

  return (
    <main className="p-8 max-w-lg mx-auto">
      <h1 className="text-2xl font-bold mb-6">New ${Name}</h1>
      <form
        onSubmit={e => { e.preventDefault(); create.mutate(form as any); }}
        className="flex flex-col gap-4"
      >
${inputs}
        <div className="flex gap-3 mt-2">
          <button type="submit" disabled={create.isPending}
            className="px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm hover:bg-indigo-700 disabled:opacity-50">
            {create.isPending ? 'Saving…' : 'Create'}
          </button>
          <button type="button" onClick={() => router.push('/${slug}')}
            className="px-4 py-2 bg-gray-100 rounded-lg text-sm hover:bg-gray-200">
            Cancel
          </button>
        </div>
        {create.error && <p className="text-red-500 text-sm">{create.error.message}</p>}
      </form>
    </main>
  );
}
`;
}

function buildEditPage(model: Model, slug: string, mCamel: string): string {
  const Name   = model.name;
  const fields = (model.fields as NamedField[]).filter(f => !['id', 'uuid', 'ulid'].includes(f.type)).slice(0, 10);
  const stateInit    = fields.map(f => `${f.name}: ${stateInitValue(f)}`).join(', ');
  const effectFields = fields.map(f => `        ${f.name}: data.${f.name} ?? ${stateInitValue(f)},`).join('\n');
  const inputs       = fields.map(f => buildFieldInput(f)).join('\n');

  return `'use client';
import { useState, useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import { api } from '~/trpc/react';

export default function ${Name}EditPage() {
  const router = useRouter();
  const params = useParams<{ id: string }>();
  const id = Number(params.id);
  const [form, setForm] = useState({ ${stateInit} });

  const query = api.${mCamel}.getById.useQuery({ id }, { enabled: !isNaN(id) });
  const utils = api.useUtils();
  const update = api.${mCamel}.update.useMutation({
    onSuccess: () => { utils.${mCamel}.getAll.invalidate(); router.push('/${slug}'); },
  });

  useEffect(() => {
    if (query.data) {
      const data = query.data;
      setForm({
${effectFields}
      });
    }
  }, [query.data]);

  if (query.isLoading) return <p className="p-8 text-gray-500">Loading…</p>;
  if (query.isError)   return <p className="p-8 text-red-500">{query.error?.message}</p>;

  return (
    <main className="p-8 max-w-lg mx-auto">
      <h1 className="text-2xl font-bold mb-6">Edit ${Name}</h1>
      <form
        onSubmit={e => { e.preventDefault(); update.mutate({ id, ...form } as any); }}
        className="flex flex-col gap-4"
      >
${inputs}
        <div className="flex gap-3 mt-2">
          <button type="submit" disabled={update.isPending}
            className="px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm hover:bg-indigo-700 disabled:opacity-50">
            {update.isPending ? 'Saving…' : 'Save'}
          </button>
          <button type="button" onClick={() => router.push('/${slug}')}
            className="px-4 py-2 bg-gray-100 rounded-lg text-sm hover:bg-gray-200">
            Cancel
          </button>
        </div>
        {update.error && <p className="text-red-500 text-sm">{update.error.message}</p>}
      </form>
    </main>
  );
}
`;
}
